/* Triela Checklists — tutorial completo, guiado e específico por perfil */
(function(){
  'use strict';
  const VERSION='tour-2026-09-04-v3';
  let role='admin',index=0,steps=[],focusEl=null,waiting=false;
  const O=()=>window.TRIELA_OFFICIAL||{};
  const P=()=>O().profile;
  const roleNames={admin:'Administrador',manager:'Gestor/Líder',collaborator:'Colaborador/Operacional'};
  const defaults={admin:['overview','execute','correct','analyze','models','builder','training','help','users','settings'],manager:['overview','execute','correct','analyze','training','help'],collaborator:['routine','training','help']};
  const actualRole=()=>P()?.role==='admin'?'admin':P()?.role==='manager'?'manager':'collaborator';
  const permissionsFor=r=>{const p=P(),found=(state.roles||[]).find(x=>x.id===p?.access_profile_id);return new Set(found?.permissions?.length?found.permissions:(defaults[r]||[]));};
  const guides={
    admin:[
      {cat:'Começando',title:'Bem-vindo ao Triela Checklists',text:'Este tour mostra o fluxo completo do Administrador. Você verá como estruturar a empresa, criar controles, cadastrar pessoas, distribuir tarefas, acompanhar desvios e analisar resultados.',bullets:['Avançar no tutorial não cria dados nem execuções.','Cada etapa abre a tela correspondente para você aprender vendo.','O tour pode ser refeito no Centro de Ajuda.'],result:'Ao final, você saberá operar o sistema do cadastro inicial até a análise gerencial.',page:'overview',focus:'.overview-greeting'},
      {perm:'overview',cat:'Visão geral',title:'Leia os indicadores principais primeiro',text:'A Visão Geral concentra o que precisa da sua atenção antes de você entrar nos detalhes.',bullets:['Conformidade mostra a qualidade das execuções realizadas.','Checklists concluídos e atrasados mostram disciplina de execução.','Não conformidades abertas indicam problemas que ainda precisam de tratamento.'],result:'Use esses números para definir a prioridade do dia.',page:'overview',focus:'#overviewKpis'},
      {perm:'overview',cat:'Visão geral',title:'Filtre por loja ou unidade',text:'O filtro de unidade muda o recorte de toda a leitura para você separar resultado geral de problema local.',bullets:['“Todas as unidades” mostra o consolidado.','Escolha uma loja para investigar apenas aquele local.','Os indicadores devem refletir somente dados reais registrados.'],result:'Você descobre rapidamente se o problema é geral ou concentrado em uma loja.',page:'overview',focus:'#overviewUnit'},
      {perm:'overview',cat:'Visão geral',title:'Entenda o Pulso Operacional',text:'O Pulso Operacional resume a saúde da operação em um score único.',bullets:['Execução no prazo mede cumprimento da rotina.','Conformidade mede a qualidade das respostas.','Ações resolvidas mostram a capacidade de corrigir problemas.'],result:'O círculo acompanha o score real; sem dados, o sistema não deve inventar resultado.',page:'overview',focus:'.ov-pulse'},
      {perm:'overview',cat:'Visão geral',title:'Acompanhe tendências, desvios e reincidências',text:'A parte inferior do painel ajuda a sair do número geral e encontrar a origem dos problemas.',bullets:['Evolução mostra se a operação melhora ou piora ao longo do tempo.','Desvios por origem mostram onde os erros se concentram.','Reincidências revelam problemas que voltam a acontecer.'],result:'Você passa de “quanto está ruim” para “onde devemos agir”.',page:'overview',focus:'.ov-bottom'},
      {perm:'execute',cat:'Checklists',title:'Conheça os checklists disponíveis',text:'Aqui ficam os controles liberados para execução e gestão.',bullets:['Cada checklist possui nome, categoria e perguntas próprias.','Execuções concluídas alimentam histórico, indicadores e relatórios.','O Administrador e o Gestor podem decidir como cada checklist chegará ao operacional.'],result:'Você controla quais rotinas existem e como serão executadas.',page:'execute',focus:'#executeCards'},
      {perm:'execute',cat:'Distribuição',title:'Direcione uma atividade para uma pessoa específica',text:'Use “Designar atividade” quando a responsabilidade precisa ter dono definido.',bullets:['Escolha checklist, loja, colaborador, frequência, data e horário.','A atividade aparecerá em “Minha Rotina” somente para o usuário escolhido.','O cumprimento pode ser acompanhado como pendente, concluído ou atrasado.'],result:'A responsabilidade fica clara e rastreável.',page:'execute',focus:'#officialAssignmentsPanel'},
      {perm:'execute',cat:'Distribuição',title:'Deixe um checklist aberto para qualquer operacional da loja',text:'Use “Abrir para loja” quando qualquer colaborador operacional autorizado naquela unidade puder executar o checklist.',bullets:['Escolha o checklist e a loja.','Não é necessário escolher uma pessoa específica.','O checklist aparece na área de checklists abertos da rotina dos usuários daquela loja.','Ele pode ser executado sempre que a operação precisar, sem virar uma pendência individual.'],result:'Você combina tarefas obrigatórias com controles disponíveis sob demanda.',page:'execute',focus:'#openChecklistManagementPanel'},
      {perm:'execute',cat:'Execuções',title:'Consulte o histórico de execuções',text:'As execuções recentes mostram o que foi feito, quando foi feito e qual resultado foi obtido.',bullets:['Confira status, conformidade e quantidade de não conformidades.','Use o histórico para investigar falhas e recorrências.','Treinamento e operação real permanecem separados.'],result:'Você mantém rastreabilidade de cada controle executado.',page:'execute',focus:'#runsTable'},
      {perm:'correct',cat:'Tratativas',title:'Feche o ciclo das não conformidades',text:'Registrar o problema é só o começo. A área de tratativas existe para garantir correção, responsável e prazo.',bullets:['Veja problema, origem, responsável, prazo e status.','Priorize itens vencidos, críticos e reincidentes.','Acompanhe a ação até a validação e o encerramento.'],result:'Nenhum desvio importante fica apenas registrado sem acompanhamento.',page:'correct',focus:'#actionsTable'},
      {perm:'analyze',cat:'Análises',title:'Transforme execução em decisão gerencial',text:'A área Análises consolida tendências e concentrações de desvio para apoiar decisões.',bullets:['Use períodos para comparar comportamento ao longo do tempo.','Observe categorias que mais impactam o resultado.','Ataque primeiro os itens frequentes e críticos.'],result:'Os dados passam a orientar prioridade, cobrança e melhoria.',page:'analyze',focus:'.analysis-main'},
      {perm:'analyze',cat:'Análises',title:'Investigue recorrências e principais problemas',text:'Os rankings mostram o que mais se repete e onde uma análise de causa pode gerar maior resultado.',bullets:['Quantidade alta indica frequência.','Criticidade alta indica impacto.','Frequência + criticidade definem prioridade real.'],result:'Você identifica os problemas que merecem causa raiz e plano de ação mais forte.',page:'analyze',focus:'.analysis-lower'},
      {perm:'models',cat:'Modelos',title:'Use modelos como ponto de partida',text:'A biblioteca ajuda a acelerar a criação sem obrigar sua empresa a copiar processos prontos.',bullets:['Escolha um modelo compatível com a rotina.','Adapte perguntas e regras à realidade da empresa.','Mantenha padronização entre unidades.'],result:'Você implanta controles com mais velocidade e consistência.',page:'models',focus:'#modelCards'},
      {perm:'builder',cat:'Construtor',title:'Crie um checklist do zero',text:'No Construtor você define a identidade e o objetivo do checklist.',bullets:['Informe nome, categoria e descrição.','Use nomes claros para facilitar busca, designação e relatórios.','Depois de salvar, selecione o checklist para adicionar perguntas.'],result:'O checklist nasce organizado e pronto para receber regras.',page:'builder',focus:'#builder .formcard'},
      {perm:'builder',cat:'Construtor',title:'Configure perguntas, criticidade e automações',text:'Cada pergunta pode representar um controle simples ou uma regra operacional importante.',bullets:['Escolha o tipo de resposta adequado.','Defina criticidade para diferenciar impacto baixo, alto ou crítico.','Ative geração de ação quando uma reprovação exigir tratamento.'],result:'O checklist deixa de ser apenas formulário e passa a controlar o processo.',page:'builder',focus:'#builder .panel'},
      {perm:'users',cat:'Equipe',title:'Cadastre usuários e defina o acesso',text:'Em Equipe e acessos você controla quem entra no sistema e o que cada pessoa pode fazer.',bullets:['Cadastre nome, usuário, função/cargo e data de nascimento.','Escolha perfil de acesso e loja ou lojas permitidas.','O Operacional fica ligado à loja definida pelo Administrador.'],result:'Cada usuário acessa somente o que corresponde à sua função e unidade.',page:'users',focus:'#users .headline'},
      {perm:'users',cat:'Equipe',title:'Entenda a senha e o código de primeiro acesso',text:'Todo novo usuário recebe senha inicial e um código individual de primeiro acesso.',bullets:['O código é exclusivo daquele usuário e usado uma única vez.','Depois do primeiro acesso, o colaborador continua com usuário e senha.','O próprio usuário pode trocar a senha em Meu perfil.','O Administrador pode gerar um novo código quando necessário.'],result:'Você controla a entrada inicial sem compartilhar contas genéricas.',page:'users',focus:'#usersTable'},
      {perm:'settings',cat:'Perfis',title:'Crie perfis e defina permissões',text:'Perfis determinam a experiência e as áreas que cada função poderá acessar.',bullets:['Administrativo: gestão completa conforme permissões.','Gestão: acompanhamento, análises, tratativas e distribuição de atividades.','Operacional: execução da rotina, treinamento e ajuda.','Perfis personalizados podem receber somente as funções necessárias.'],result:'Você consegue criar funções próprias sem liberar acesso além do necessário.',page:'settings',focus:'#rolesAdminList'},
      {perm:'settings',cat:'Estrutura',title:'Cadastre lojas e organize a empresa',text:'As lojas/unidades ligam usuários, execuções, filtros e histórico ao local correto.',bullets:['Cadastre nome, código, cidade e regional/grupo quando necessário.','Vincule cada usuário às unidades permitidas.','Quando houver histórico, preserve os registros em vez de simplesmente apagá-los.'],result:'A plataforma fica pronta para crescer de uma loja para várias unidades.',page:'settings',focus:'#unitsAdminList'},
      {perm:'settings',cat:'Configurações',title:'Entenda regras gerais e score operacional',text:'As configurações concentram parâmetros que influenciam tratativas e indicadores.',bullets:['Defina prazos e responsáveis padrão quando aplicável.','Entenda os pesos de execução, conformidade, correção e prazo.','Revise as regras antes de expandir o uso oficial.'],result:'Os indicadores passam a seguir uma lógica padronizada e conhecida.',page:'settings',focus:'#settings .grid2'},
      {perm:'training',cat:'Treinamento',title:'Treine sem contaminar a operação real',text:'O Modo Treinamento permite praticar o processo com segurança.',bullets:['Execuções de treinamento ficam separadas da operação oficial.','Treinamento não deve alterar indicadores, atrasos ou rankings reais.','Use este ambiente antes de liberar novos colaboradores para a operação.'],result:'Você ensina o sistema sem gerar dados falsos.',page:'training',focus:'#training .headline'},
      {perm:'help',cat:'Ajuda',title:'Use o Centro de Ajuda para reciclagem',text:'O tutorial continua disponível mesmo depois do primeiro acesso.',bullets:['Refaça o tour sempre que precisar.','Use a ajuda durante treinamentos internos.','Cada perfil recebe explicações compatíveis com suas permissões.'],result:'O conhecimento permanece disponível dentro do próprio sistema.',page:'help',focus:'#help .helpgrid'},
      {cat:'Conta e ambiente',title:'Conheça os controles do topo e o Meu perfil',text:'A barra superior identifica o ambiente atual e reúne atalhos. O cartão do usuário abre as opções pessoais da conta.',bullets:['Operação real e Treinamento deixam claro onde você está trabalhando.','Exportação e impressão ficam disponíveis conforme a tela e permissão.','“Visualizar como” é apenas uma prévia para Administrador; não substitui as permissões reais.','Em Meu perfil o usuário pode trocar a própria senha e sair do sistema.'],result:'Você diferencia ambiente, visualização e segurança real da conta.',page:'overview',focus:'.top-actions'},
      {cat:'Finalização',title:'Fluxo completo do Administrador',text:'A lógica do Triela é: estruturar, controlar, distribuir, executar, corrigir e melhorar.',bullets:['Configurar empresa e pessoas.','Criar checklists e definir como serão disponibilizados.','Acompanhar execução, desvios e ações.','Analisar os resultados e melhorar o processo.'],result:'Tutorial concluído. Você pode refazê-lo a qualquer momento no Centro de Ajuda.',page:'overview',focus:'.overview-greeting'}
    ],
    manager:[
      {cat:'Começando',title:'Bem-vindo ao painel de Gestão',text:'Seu perfil foi feito para acompanhar a operação, distribuir atividades, tratar desvios e usar os indicadores para tomar decisões.',bullets:['Você verá somente as funções liberadas para seu perfil.','Nada será registrado apenas por avançar no tutorial.','O tour pode ser refeito no Centro de Ajuda.'],result:'Ao final, você saberá acompanhar a rotina da equipe do início ao fim.',page:'overview',focus:'.overview-greeting'},
      {perm:'overview',cat:'Visão geral',title:'Comece pelas prioridades da operação',text:'Veja conformidade, execuções, atrasos e não conformidades antes de entrar nos detalhes.',bullets:['Use os KPIs para identificar o que precisa de atenção.','Filtre pelas lojas que estão sob sua responsabilidade.','Observe o Pulso Operacional para uma leitura resumida da saúde da operação.'],result:'Você decide rapidamente onde concentrar a gestão.',page:'overview',focus:'#overviewKpis'},
      {perm:'overview',cat:'Visão geral',title:'Use tendências e reincidências',text:'Não olhe apenas o número do dia: acompanhe como os resultados mudam e quais problemas estão voltando.',bullets:['Evolução mostra tendência.','Desvios mostram concentração.','Reincidências mostram falhas que exigem ação mais profunda.'],result:'Você evita tratar sempre o mesmo problema de forma superficial.',page:'overview',focus:'.ov-bottom'},
      {perm:'execute',cat:'Checklists',title:'Acompanhe e execute os checklists permitidos',text:'Na área Checklists você consulta os modelos e o histórico liberados para suas unidades.',bullets:['Confira o checklist correto antes de iniciar.','Execuções reais alimentam os indicadores.','Use o histórico para conferir resultado e não conformidades.'],result:'Você mantém rastreabilidade da rotina das lojas sob sua responsabilidade.',page:'execute',focus:'#executeCards'},
      {perm:'execute',cat:'Distribuição',title:'Designe tarefas para usuários específicos',text:'Quando uma atividade precisa ter dono, escolha o usuário responsável.',bullets:['Defina checklist, loja, colaborador, data, horário e frequência.','A atividade entra na Minha Rotina do usuário escolhido.','Atrasos e conclusões ficam visíveis para acompanhamento.'],result:'A gestão sabe exatamente quem deveria fazer cada tarefa.',page:'execute',focus:'#officialAssignmentsPanel'},
      {perm:'execute',cat:'Distribuição',title:'Disponibilize checklists abertos para a loja',text:'Alguns controles não precisam ter uma pessoa fixa. Eles podem ficar disponíveis para qualquer operacional autorizado da loja.',bullets:['Selecione checklist e unidade.','Qualquer operacional daquela loja poderá executar quando necessário.','Checklist aberto não vira pendência pessoal para todos os colaboradores.'],result:'Você consegue combinar rotina obrigatória com execução sob demanda.',page:'execute',focus:'#openChecklistManagementPanel'},
      {perm:'correct',cat:'Tratativas',title:'Trate os desvios até o encerramento',text:'Acompanhe não conformidades e planos de ação para garantir que o problema realmente seja corrigido.',bullets:['Defina responsável e prazo.','Priorize itens críticos e vencidos.','Valide a solução antes de considerar o problema encerrado.'],result:'A gestão fecha o ciclo entre identificar e corrigir.',page:'correct',focus:'#actionsTable'},
      {perm:'analyze',cat:'Análises',title:'Use os dados para cobrar e melhorar',text:'As análises ajudam a enxergar tendências, categorias de problema e reincidências.',bullets:['Compare períodos.','Veja onde a conformidade piora.','Concentre esforços nos problemas frequentes e críticos.'],result:'Sua cobrança passa a ser baseada em evidência, não apenas percepção.',page:'analyze',focus:'.analysis-main'},
      {perm:'training',cat:'Treinamento',title:'Treine a equipe em ambiente separado',text:'Use o ambiente de treinamento para ensinar a execução sem alterar os dados oficiais.',bullets:['Pratique o processo antes da operação real.','Use para reciclagem de equipe.','Dados simulados não devem afetar o resultado oficial.'],result:'Você capacita sem contaminar os indicadores.',page:'training',focus:'#training .headline'},
      {perm:'help',cat:'Ajuda',title:'Refaça o tutorial quando precisar',text:'O Centro de Ajuda fica disponível para consulta e reciclagem.',bullets:['Reabra este tour.','Use a ajuda para orientar novos líderes.','Consulte explicações durante a operação.'],result:'O suporte de uso fica dentro do próprio sistema.',page:'help',focus:'#help .helpgrid'},
      {cat:'Finalização',title:'Fluxo completo do Gestor/Líder',text:'A rotina de gestão é: observar, distribuir, acompanhar, tratar e analisar.',bullets:['Veja prioridades.','Distribua atividades.','Acompanhe execução e atrasos.','Trate os desvios.','Use os dados para melhorar.'],result:'Tutorial concluído. Você pode refazê-lo no Centro de Ajuda.',page:'overview',focus:'.overview-greeting'}
    ],
    collaborator:[
      {cat:'Começando',title:'Bem-vindo à sua rotina operacional',text:'Seu acesso foi simplificado para mostrar principalmente o que você precisa fazer no dia, sem telas administrativas.',bullets:['Você não cria checklists nem perfis.','Você não vê dados de outras lojas.','Você executa atividades designadas e checklists abertos da sua própria loja.'],result:'Ao final, você saberá exatamente onde encontrar e executar seu trabalho.',page:'routine',focus:'.routine-hero'},
      {perm:'routine',cat:'Minha Rotina',title:'Veja sua próxima atividade',text:'A atividade mais importante aparece em destaque com horário, checklist e informações da execução.',bullets:['Atividades designadas têm você como responsável.','Se houver atraso, o sistema identifica a pendência.','Use “Iniciar” para abrir o checklist correspondente.'],result:'Você começa o trabalho sem precisar procurar a tarefa em várias telas.',page:'routine',focus:'.routine-hero'},
      {perm:'routine',cat:'Minha Rotina',title:'Entenda seu progresso do dia',text:'O círculo mostra quanto da sua rotina pessoal obrigatória já foi concluído.',bullets:['Concluídos contam atividades finalizadas.','Pendentes mostram o que ainda falta.','Atrasados mostram atividades cujo prazo já passou.','Checklists abertos da loja não contam como pendência pessoal.'],result:'Você sabe rapidamente se sua rotina está em dia.',page:'routine',focus:'.routine-progress-card'},
      {perm:'routine',cat:'Minha Rotina',title:'Use as listas Hoje, Próximas e Concluídas',text:'As abas organizam sua agenda para você separar o que precisa fazer agora do que já terminou.',bullets:['Hoje mostra atividades do dia e atrasadas.','Próximas mostra o que ainda virá.','Concluídas permite conferir o que você já realizou.'],result:'Sua agenda fica organizada por situação.',page:'routine',focus:'.routine-list-wrap'},
      {perm:'routine',cat:'Checklists abertos',title:'Execute controles disponíveis para qualquer operacional da loja',text:'Além das tarefas que têm seu nome, a empresa pode deixar alguns checklists abertos para qualquer operacional autorizado da sua unidade.',bullets:['Eles aparecem em uma área separada na Minha Rotina.','Você pode executar quando a situação exigir.','Eles não aparecem como atraso individual se você não fizer.','Usuários de outras lojas não conseguem acessá-los.'],result:'Você tem autonomia para executar controles sob demanda sem acessar o Construtor.',page:'routine',focus:'#openChecklistRoutinePanel'},
      {cat:'Execução',title:'Responda o checklist com atenção',text:'Ao iniciar uma atividade, responda cada pergunta conforme o que realmente encontrou na operação.',bullets:['Leia a pergunta antes de responder.','Registre evidências quando forem solicitadas.','Uma resposta não conforme pode abrir uma tratativa automaticamente.','Finalize somente depois de conferir as respostas.'],result:'Sua execução fica registrada com usuário, loja, data e resultado.',page:'routine',focus:'.routine-tip'},
      {perm:'training',cat:'Treinamento',title:'Pratique antes de usar na operação real',text:'No Modo Treinamento você pode aprender o processo sem afetar os indicadores oficiais.',bullets:['Use para praticar a navegação.','Treinamento fica separado da operação real.','Pergunte ao seu líder antes de usar treinamento como rotina oficial.'],result:'Você ganha segurança antes de executar tarefas reais.',page:'training',focus:'#training .headline'},
      {perm:'help',cat:'Ajuda',title:'Consulte ajuda sempre que tiver dúvida',text:'O Centro de Ajuda permite rever este tutorial e consultar explicações do sistema.',bullets:['Refaça o tour quantas vezes precisar.','Use a ajuda durante sua adaptação ao sistema.','Se uma função não aparecer, ela pode não estar liberada para seu perfil.'],result:'Você não precisa decorar tudo no primeiro dia.',page:'help',focus:'#help .helpgrid'},
      {cat:'Conta',title:'Troque sua própria senha em Meu perfil',text:'Clique no seu nome/avatar na barra lateral para abrir as opções da sua conta.',bullets:['Você pode definir uma nova senha.','Sua senha atual nunca é mostrada ao Administrador.','Use “Sair do sistema” ao terminar em um aparelho compartilhado.'],result:'Sua conta continua pessoal e protegida.',page:'routine',focus:'.profile'},
      {cat:'Finalização',title:'Fluxo do Operacional',text:'Sua rotina é simples: abrir Minha Rotina, executar o que foi designado, usar checklists abertos quando necessário e finalizar corretamente.',bullets:['Ver tarefa.','Executar checklist.','Registrar o que encontrou.','Finalizar.','Consultar ajuda quando precisar.'],result:'Tutorial concluído. Você pode refazê-lo a qualquer momento.',page:'routine',focus:'.routine-hero'}
    ]
  };

  function injectStyle(){if(document.getElementById('trielaTourStyle'))return;const s=document.createElement('style');s.id='trielaTourStyle';s.textContent=`.triela-tour-focus{position:relative!important;z-index:10002!important;outline:4px solid #6d5dfc!important;outline-offset:5px!important;border-radius:14px!important;box-shadow:0 0 0 9999px rgba(5,18,43,.18)!important}.tour-v3{max-width:720px!important}.tour-v3 .tutorial-step{padding:4px 0}.tour-v3 .tour-cat{font-size:11px;font-weight:900;letter-spacing:.12em;color:#6d5dfc;text-transform:uppercase}.tour-v3 .tour-result{margin-top:14px;padding:12px 14px;border-radius:12px;background:#eefaf7;color:#075f54;font-size:13px}.tour-v3 .tour-result strong{display:block;margin-bottom:3px}.tour-v3 .tour-count{font-size:12px;color:#64748b;margin-top:4px}.tour-v3 .tour-role-note{font-size:12px;color:#64748b;margin-top:7px}.tour-v3 .tutorial-step li{margin:7px 0;line-height:1.45}.tour-v3 .tutorial-step p{line-height:1.55}.tour-v3 .tutorial-progress span{transition:width .25s ease}`;document.head.appendChild(s);}
  function clearFocus(){if(focusEl){focusEl.classList.remove('triela-tour-focus');focusEl=null;}}
  function highlight(selector){clearFocus();if(!selector)return;setTimeout(()=>{const el=document.querySelector(selector);if(!el)return;focusEl=el;el.classList.add('triela-tour-focus');try{el.scrollIntoView({behavior:'smooth',block:'center'});}catch{}},80);}
  function canSwitchRole(){return O().ready&&actualRole()==='admin';}
  function buildSteps(r){const perms=permissionsFor(r);return (guides[r]||[]).filter(x=>!x.perm||perms.has(x.perm));}
  function keyFor(r){return `triela-tour-version:${P()?.user_id||'local'}:${r}`;}

  window.showTutorial=function(force=false,requested=null){
    injectStyle();
    if(window.TRIELA_OFFICIAL&&!O().ready){if(!waiting){waiting=true;setTimeout(()=>{waiting=false;showTutorial(force,requested);},700);}return;}
    const real=actualRole();role=(canSwitchRole()&&requested&&guides[requested])?requested:real;
    if(!force&&localStorage.getItem(keyFor(role))===VERSION)return;
    steps=buildSteps(role);index=0;renderTour();
  };
  window.renderTutorial=function(){renderTour();};
  function renderTour(){
    clearFocus();if(!steps.length)return;const step=steps[index],pct=Math.round((index+1)/steps.length*100);if(step.page&&typeof navigate==='function')navigate(step.page);
    const root=document.getElementById('modalRoot');if(!root)return;
    const picker=canSwitchRole()?`<div class="tutorial-role-picker"><button class="${role==='admin'?'active':''}" onclick="changeTutorialRole('admin')">Administrador</button><button class="${role==='manager'?'active':''}" onclick="changeTutorialRole('manager')">Gestor/Líder</button><button class="${role==='collaborator'?'active':''}" onclick="changeTutorialRole('collaborator')">Operacional</button></div>`:'';
    root.innerHTML=`<div class="modalback"><div class="modal tour-v3"><div class="modalhead"><div><div class="eyebrow">PRIMEIRO ACESSO · ${roleNames[role]}</div><h2 style="margin:4px 0;color:var(--navy)">Tutorial completo do seu perfil</h2>${picker}<div class="tour-role-note">O conteúdo abaixo mostra somente funções compatíveis com este perfil.</div></div><button class="iconbtn" onclick="finishTutorial(false)">×</button></div><div class="modalbody"><div class="tutorial-progress"><span style="width:${pct}%"></span></div><div class="tutorial-step"><div class="tour-cat">${step.cat||'Etapa'}</div><div class="stepnum">Passo ${index+1} de ${steps.length}</div><h2>${step.title}</h2><p>${step.text}</p>${step.bullets?`<ul>${step.bullets.map(x=>`<li>${x}</li>`).join('')}</ul>`:''}<div class="tour-result"><strong>O que você aprende nesta etapa</strong>${step.result||''}</div><span class="tutorial-page-pill">Tela demonstrada: ${typeof pageLabel==='function'?pageLabel(step.page):step.page}</span></div></div><div class="modalfooter"><button class="btn secondary" onclick="finishTutorial(false)">Pular por agora</button>${index>0?'<button class="btn secondary" onclick="tutorialPrev()">Voltar</button>':''}<button class="btn" onclick="tutorialNext()">${index===steps.length-1?'Concluir tutorial':'Próximo'}</button></div></div></div>`;
    highlight(step.focus);
  }
  window.changeTutorialRole=function(r){if(!canSwitchRole())return;role=r;steps=buildSteps(role);index=0;renderTour();};
  window.tutorialNext=function(){if(index<steps.length-1){index++;renderTour();}else finishTutorial(true);};
  window.tutorialPrev=function(){if(index>0){index--;renderTour();}};
  window.finishTutorial=function(completed=true){clearFocus();const root=document.getElementById('modalRoot');if(root)root.innerHTML='';if(completed){localStorage.setItem(keyFor(role),VERSION);state.ui=state.ui||{};state.ui.tutorialDone=true;state.ui.tutorialDoneByRole=state.ui.tutorialDoneByRole||{};state.ui.tutorialDoneByRole[role]=true;try{save();}catch{}if(typeof toast==='function')toast('Tutorial concluído. Você pode refazê-lo no Centro de Ajuda.');}if(typeof applyRoleView==='function')applyRoleView();};

  /* Garante que a nova versão do tour apareça uma vez para cada usuário após a atualização. */
  setTimeout(()=>showTutorial(false,null),1100);
})();
