const seed={templates:[
{id:'t1',name:'Ronda Preventiva de Loja',category:'Prevenção de Perdas',description:'Ronda estruturada por áreas críticas, riscos, evidências e tratativas.',questions:[{id:'q1',title:'Produtos de alto risco estão protegidos e expostos corretamente?',type:'conform',critical:'high',action:true},{id:'q2',title:'Há pontos cegos ou áreas sem cobertura de observação?',type:'yesno',critical:'critical',action:true},{id:'q3',title:'Recepção e frente de caixa estão organizadas?',type:'conform',critical:'medium',action:true}]},
{id:'t2',name:'Recebimento de Mercadorias',category:'Recebimento',description:'Conferência de carga, NF, avarias, divergências e liberação.',questions:[{id:'q4',title:'Quantidade física confere com a nota fiscal?',type:'conform',critical:'critical',action:true},{id:'q5',title:'Existem avarias na carga?',type:'yesno',critical:'high',action:true},{id:'q6',title:'Temperatura do produto refrigerado',type:'number',critical:'high',action:true}]},
{id:'t3',name:'Controle de Validade / FEFO',category:'Validade',description:'Auditoria de validade, organização e aplicação do FEFO.',questions:[{id:'q7',title:'Produtos mais próximos do vencimento estão à frente?',type:'conform',critical:'high',action:true},{id:'q8',title:'Existem produtos vencidos na área?',type:'yesno',critical:'critical',action:true}]},
{id:'t4',name:'Limpeza e 5S',category:'Qualidade',description:'Organização, limpeza, identificação e padronização visual.',questions:[{id:'q9',title:'Área está limpa e sem resíduos?',type:'conform',critical:'medium',action:true},{id:'q10',title:'Materiais estão identificados e armazenados corretamente?',type:'conform',critical:'medium',action:true}]},
{id:'t5',name:'Temperatura de Equipamentos',category:'Temperatura',description:'Registro de temperatura com faixas de mínimo, máximo e média.',questions:[{id:'q11',title:'Temperatura medida (°C)',type:'number',critical:'critical',action:true},{id:'q12',title:'Equipamento apresenta sinais de falha?',type:'yesno',critical:'high',action:true}]},
{id:'t6',name:'Auditoria Operacional',category:'Auditoria',description:'Checklist pontuado para avaliar conformidade geral da operação.',questions:[{id:'q13',title:'Processo está sendo executado conforme padrão?',type:'conform',critical:'high',action:true},{id:'q14',title:'Nota geral da área',type:'score',critical:'medium',action:false}]}
],runs:[
{id:'r1',templateId:'t1',date:'2026-09-03T11:20:00',status:'completed',compliance:82,nc:2,answers:[{qid:'q1',ok:false,label:'Não conforme'},{qid:'q2',ok:true,label:'Não'},{qid:'q3',ok:false,label:'Não conforme'}]},
{id:'r2',templateId:'t2',date:'2026-09-03T09:10:00',status:'completed',compliance:94,nc:1,answers:[{qid:'q4',ok:true,label:'Conforme'},{qid:'q5',ok:false,label:'Sim'},{qid:'q6',ok:true,label:'4.2'}]},
{id:'r3',templateId:'t3',date:'2026-09-02T15:40:00',status:'completed',compliance:88,nc:1,answers:[{qid:'q7',ok:false,label:'Não conforme'},{qid:'q8',ok:true,label:'Não'}]},
{id:'r4',templateId:'t4',date:'2026-09-02T10:30:00',status:'completed',compliance:100,nc:0,answers:[]},
{id:'r5',templateId:'t5',date:'2026-09-01T14:10:00',status:'completed',compliance:78,nc:1,answers:[{qid:'q11',ok:false,label:'11.8'},{qid:'q12',ok:true,label:'Não'}]},
{id:'r6',templateId:'t6',date:'2026-09-01T08:50:00',status:'completed',compliance:91,nc:1,answers:[{qid:'q13',ok:false,label:'Não conforme'}]},
{id:'r7',templateId:'t1',date:'2026-09-03T16:10:00',status:'in_progress',compliance:0,nc:0,answers:[]}
],actions:[
{id:'a1',title:'Corrigir exposição de produto de alto risco',origin:'Ronda Preventiva de Loja',owner:'Carlos',due:'2026-09-03T18:00:00',status:'overdue'},
{id:'a2',title:'Tratar avaria encontrada no recebimento',origin:'Recebimento de Mercadorias',owner:'Mariana',due:'2026-09-04T10:00:00',status:'pending'},
{id:'a3',title:'Reorganizar FEFO do setor de frios',origin:'Controle de Validade / FEFO',owner:'João',due:'2026-09-05T12:00:00',status:'pending'},
{id:'a4',title:'Avaliar equipamento com temperatura fora do padrão',origin:'Temperatura de Equipamentos',owner:'Manutenção',due:'2026-09-03T17:00:00',status:'overdue'},
{id:'a5',title:'Padronizar recepção da prevenção',origin:'Ronda Preventiva de Loja',owner:'André',due:'2026-09-02T16:00:00',status:'done'}
],users:[{name:'André Lima',role:'Administrador',unit:'Matriz',runs:18,compliance:93,active:true},{name:'Carlos Silva',role:'Executor',unit:'Matriz',runs:31,compliance:90,active:true},{name:'Mariana Souza',role:'Gestora',unit:'Shopping',runs:27,compliance:95,active:true},{name:'João Pedro',role:'Auditor',unit:'Matriz',runs:22,compliance:88,active:true}]};