/* Triela Checklists — analytics reais e drill-down de inconformidades */
(function(){
'use strict';
const O=()=>window.TRIELA_OFFICIAL||{}, DB=()=>O().supabase;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sev=v=>({critical:'Crítica',high:'Alta',medium:'Média',low:'Baixa'})[v]||v||'—';
const st=v=>({open:'Aberta',in_treatment:'Em tratamento',awaiting_validation:'Aguardando validação',resolved:'Resolvida',pending:'Pendente',completed:'Concluída',overdue:'Atrasada'})[v]||String(v||'—').replaceAll('_',' ');
const dt=v=>v?new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—';
const dk=v=>{const d=new Date(v);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const pct=v=>Number.isFinite(Number(v))?`${Number(v).toFixed(1).replace('.',',')}%`:'—';
const norm=s=>String(s||'').toLocaleLowerCase('pt-BR').trim();
let data=null, loading=null, ovDays=7, anDays=30, filter={q:'',cat:'all',store:'all',sev:'all',status:'all'};
function by(a,k='id'){return new Map((a||[]).map(x=>[x[k],x]))}
function maps(){return{e:by(data.execs),n:by(data.ncs),t:by(data.templates),i:by(data.items),s:by(data.stores),p:by(data.people,'user_id'),r:by(data.responses),a:new Map(data.actions.map(x=>[x.nonconformity_id,x]))}}
async function load(force=false){
 if(!O().ready||!DB())return null;if(data&&!force&&Date.now()-data.at<15000)return data;if(loading)return loading;
 loading=(async()=>{const db=DB(),[e,n,a,t,i,s,p]=await Promise.all([
  db.from('cp_executions').select('id,store_id,template_id,status,completed_at,created_at,performed_by,score').eq('environment','production').order('created_at',{ascending:false}).limit(5000),
  db.from('cp_nonconformities').select('id,store_id,execution_id,response_id,item_id,title,description,severity,status,opened_at,resolved_at').eq('environment','production').order('opened_at',{ascending:false}).limit(5000),
  db.from('cp_action_plans').select('id,nonconformity_id,action_text,responsible_user_id,due_at,status,notes,completed_at,created_at').eq('environment','production').order('created_at',{ascending:false}).limit(5000),
  db.from('cp_checklist_templates').select('id,name,area'),db.from('cp_template_items').select('id,template_id,title,instructions'),db.from('cp_stores').select('id,name,city,state'),db.from('cp_profiles').select('user_id,full_name,job_title,sector')]);
  for(const q of[e,n,a,t,i,s,p])if(q.error)throw q.error;let responses=[];if(e.data?.length){const rq=await db.from('cp_responses').select('id,execution_id,item_id,value_text,value_number,value_boolean,is_na,is_compliant,notes').limit(10000);if(!rq.error)responses=rq.data||[]}
  data={at:Date.now(),execs:e.data||[],ncs:n.data||[],actions:a.data||[],templates:t.data||[],items:i.data||[],stores:s.data||[],people:p.data||[],responses};return data
 })().finally(()=>loading=null);return loading;
}
function bounds(days){const to=new Date();to.setHours(23,59,59,999);const from=new Date(to);from.setDate(from.getDate()-days+1);from.setHours(0,0,0,0);return{from,to}}
function selectedStore(){const v=document.getElementById('overviewUnit')?.value||'Todas as unidades';return v==='Todas as unidades'?'all':v}
function slice(days,store='all'){const m=maps(),b=bounds(days),ok=(id)=>store==='all'||m.s.get(id)?.name===store;return{m,execs:data.execs.filter(x=>x.status==='completed'&&new Date(x.completed_at||x.created_at)>=b.from&&ok(x.store_id)),ncs:data.ncs.filter(x=>new Date(x.opened_at)>=b.from&&ok(x.store_id))}}
function buckets(d,days){const m=new Map(),mode=days<=14?'day':days<=45?'week':'month';const key=v=>{const x=new Date(v);if(mode==='day')return dk(x);if(mode==='month')return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`;const z=new Date(x);z.setDate(z.getDate()-((z.getDay()+6)%7));return dk(z)};const label=k=>mode==='month'?new Date(k+'-01T12:00:00').toLocaleDateString('pt-BR',{month:'short'}).replace('.',''):mode==='week'?`Sem ${new Date(k+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}`:new Date(k+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'});const get=k=>{if(!m.has(k))m.set(k,{key:k,label:label(k),scores:[],execs:0,ncs:0});return m.get(k)};d.execs.forEach(x=>{const g=get(key(x.completed_at||x.created_at)),v=Number(x.score);if(Number.isFinite(v))g.scores.push(v);g.execs++});d.ncs.forEach(x=>get(key(x.opened_at)).ncs++);return[...m.values()].sort((a,b)=>a.key.localeCompare(b.key)).map(x=>({...x,score:x.scores.length?x.scores.reduce((a,b)=>a+b,0)/x.scores.length:null}))}
function chart(root,rows){if(!root)return;if(!rows.length){root.innerHTML='<div class="tri-empty"><strong>Sem dados no período</strong><span>O gráfico mostrará somente execuções reais.</span></div>';return}const W=860,H=225,L=48,R=18,T=22,B=42,PW=W-L-R,PH=H-T-B,maxN=Math.max(1,...rows.map(x=>x.ncs)),x=i=>rows.length===1?L+PW/2:L+i*PW/(rows.length-1),y=v=>T+(100-Math.max(60,Math.min(100,v)))*PH/40,pts=rows.filter(r=>r.score!==null).map(r=>({r,x:x(rows.indexOf(r)),y:y(r.score)})),path=pts.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ');root.innerHTML=`<div class="tri-chart"><div class="tri-legend"><span><i></i>Conformidade</span><span><b></b>Inconformidades</span><em>Passe o mouse ou clique</em></div><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${[60,70,80,90,100].map(v=>`<line x1="${L}" x2="${W-R}" y1="${y(v)}" y2="${y(v)}"/><text x="4" y="${y(v)+4}">${v}%</text>`).join('')}${rows.map((r,i)=>{const h=r.ncs/maxN*62;return`<rect class="tri-bar" data-key="${r.key}" data-label="${r.label}" data-nc="${r.ncs}" x="${x(i)-11}" y="${H-B-h}" width="22" height="${h}" rx="5"/>`}).join('')}${path?`<path class="tri-line" d="${path}"/>`:''}${pts.map(p=>`<circle class="tri-point" data-key="${p.r.key}" data-label="${p.r.label}" data-score="${p.r.score}" data-execs="${p.r.execs}" data-nc="${p.r.ncs}" cx="${p.x}" cy="${p.y}" r="5"/>`).join('')}${rows.map((r,i)=>`<text class="tri-x" text-anchor="middle" x="${x(i)}" y="${H-11}">${r.label}</text>`).join('')}</svg><div class="tri-tip hidden"></div></div>`;const shell=root.querySelector('.tri-chart'),tip=root.querySelector('.tri-tip');root.querySelectorAll('.tri-point,.tri-bar').forEach(el=>{const show=()=>{tip.innerHTML=`<strong>${esc(el.dataset.label)}</strong>${el.dataset.score?`<span>Conformidade <b>${pct(el.dataset.score)}</b></span><span>Execuções <b>${el.dataset.execs}</b></span>`:''}<span>Inconformidades <b>${el.dataset.nc}</b></span>`;const a=el.getBoundingClientRect(),b=shell.getBoundingClientRect();tip.style.left=Math.max(6,Math.min(b.width-172,a.left-b.left-55))+'px';tip.style.top=Math.max(4,a.top-b.top-78)+'px';tip.classList.remove('hidden')};el.onmouseenter=show;el.onmouseleave=()=>tip.classList.add('hidden');el.onclick=()=>openBucket(el.dataset.key,rows)})}
function summary(ncs,m){const z=new Map();ncs.forEach(n=>{const k=norm(n.title),e=m.e.get(n.execution_id),t=m.t.get(e?.template_id),v=z.get(k)||{title:n.title,count:0,cat:t?.area||'Sem categoria',severity:n.severity};v.count++;z.set(k,v)});return[...z.values()].sort((a,b)=>b.count-a.count)}
async function enhanceOverview(){try{await load()}catch{return}const d=slice(ovDays,selectedStore());chart(document.getElementById('complianceChart'),buckets(d,ovDays));const crit=d.ncs.filter(n=>['critical','high'].includes(n.severity)).length,card=[...document.querySelectorAll('#overviewKpis .ov-kpi')].find(x=>x.textContent.includes('Não conformidades'));if(card){const tr=card.querySelector('.ov-trend');if(tr)tr.textContent=`${crit} alta/crítica${crit===1?'':'s'}`};const byc=new Map();d.ncs.forEach(n=>{const e=d.m.e.get(n.execution_id),t=d.m.t.get(e?.template_id),c=t?.area||'Sem categoria';byc.set(c,(byc.get(c)||0)+1)});const ol=document.getElementById('originList'),arr=[...byc].sort((a,b)=>b[1]-a[1]),mx=Math.max(1,...arr.map(x=>x[1]));if(ol)ol.innerHTML=arr.length?arr.map(([c,n],i)=>`<button class="origin-row tri-click" data-cat="${esc(c)}"><span>${esc(c)}</span><div class="origin-track"><span class="c${i%4+1}" style="width:${n/mx*100}%"></span></div><strong>${n}</strong></button>`).join(''):'<div class="tri-inline-empty">Nenhuma inconformidade no período.</div>';ol?.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{filter.cat=b.dataset.cat;navigate('analyze');setTimeout(enhanceAnalysis,60)})}
function analysisData(){return slice(anDays,'all')}
function renderKpis(d){const root=document.getElementById('analysisPremiumKpis');if(!root)return;const scores=d.execs.map(x=>Number(x.score)).filter(Number.isFinite),comp=scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:null,crit=d.ncs.filter(n=>['critical','high'].includes(n.severity)).length,res=d.ncs.filter(n=>n.resolved_at).map(n=>(new Date(n.resolved_at)-new Date(n.opened_at))/86400000),avg=res.length?res.reduce((a,b)=>a+b,0)/res.length:null;root.innerHTML=[['Conformidade geral',comp===null?'—':pct(comp),'↗','purple'],['Total de NC',d.ncs.length,'!','amber'],['NC alta/crítica',crit,'△','red'],['Tempo médio resolução',avg===null?'—':avg.toFixed(1).replace('.',',')+' dias','◷','teal']].map(x=>`<div class="analysis-kpi"><div class="ak-top"><span class="ak-label">${x[0]}</span><span class="ak-icon tri-${x[3]}">${x[2]}</span></div><div class="ak-value">${x[1]}</div><div class="ak-trend">Dados reais do período</div></div>`).join('')}
function renderCats(d){const root=document.getElementById('analysisCategories');if(!root)return;const z=new Map();d.ncs.forEach(n=>{const e=d.m.e.get(n.execution_id),t=d.m.t.get(e?.template_id),c=t?.area||'Sem categoria';z.set(c,(z.get(c)||0)+1)});const a=[...z].sort((x,y)=>y[1]-x[1]),mx=Math.max(1,...a.map(x=>x[1]));root.innerHTML=a.length?a.map(([c,n])=>`<button class="cat-row tri-click ${filter.cat===c?'active':''}" data-cat="${esc(c)}"><span>${esc(c)}</span><div class="cat-track"><span style="width:${Math.max(7,n/mx*100)}%"></span></div><strong>${n}</strong></button>`).join(''):'<div class="tri-empty small"><strong>Sem desvios</strong><span>Nenhuma NC no período.</span></div>';root.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{filter.cat=filter.cat===b.dataset.cat?'all':b.dataset.cat;renderDetailPanel(d);renderCats(d)})}
function renderIssues(d){const a=summary(d.ncs,d.m),top=document.getElementById('analysisTopIssues'),rec=document.getElementById('analysisRecurrences');if(top){top.innerHTML=a.length?a.slice(0,5).map(x=>`<button class="nc-row tri-click" data-title="${esc(x.title)}"><strong>${esc(x.title)}</strong><span>${esc(x.cat)}</span><span><span class="crit-pill ${x.severity}">${sev(x.severity)}</span></span><strong>${x.count}</strong></button>`).join(''):'<div class="tri-inline-empty">Nenhuma inconformidade.</div>';top.querySelectorAll('[data-title]').forEach(b=>b.onclick=()=>{filter.q=b.dataset.title;renderDetailPanel(d);document.getElementById('triNcPanel')?.scrollIntoView({behavior:'smooth'})})}if(rec){const r=a.filter(x=>x.count>1);rec.innerHTML=r.length?r.slice(0,4).map(x=>`<button class="rec-card-item tri-click" data-title="${esc(x.title)}"><span class="dot"></span><div><strong>${esc(x.title)}</strong><small>${esc(x.cat)} • ${x.count} ocorrências</small></div><b>${x.count}x</b></button>`).join(''):'<div class="tri-empty small"><strong>Sem reincidências</strong><span>Nenhum problema se repetiu.</span></div>';rec.querySelectorAll('[data-title]').forEach(b=>b.onclick=()=>{filter.q=b.dataset.title;renderDetailPanel(d)})}}
function rows(d){return d.ncs.filter(n=>{const e=d.m.e.get(n.execution_id),t=d.m.t.get(e?.template_id),s=d.m.s.get(n.store_id),p=d.m.p.get(e?.performed_by),cat=t?.area||'Sem categoria',q=norm(filter.q);return(filter.cat==='all'||cat===filter.cat)&&(filter.store==='all'||n.store_id===filter.store)&&(filter.sev==='all'||n.severity===filter.sev)&&(filter.status==='all'||n.status===filter.status)&&(!q||norm([n.title,n.description,t?.name,s?.name,p?.full_name].join(' ')).includes(q))})}
function tableHtml(list,d){const rec=new Map(summary(d.ncs,d.m).map(x=>[norm(x.title),x.count]));return list.length?`<div class="tri-table-wrap"><table class="tri-table"><thead><tr><th>Data</th><th>Inconformidade</th><th>Checklist</th><th>Loja</th><th>Executado por</th><th>Criticidade</th><th>Status</th><th>Rec.</th><th></th></tr></thead><tbody>${list.map(n=>{const e=d.m.e.get(n.execution_id),t=d.m.t.get(e?.template_id),s=d.m.s.get(n.store_id),p=d.m.p.get(e?.performed_by);return`<tr><td>${dt(n.opened_at)}</td><td><strong>${esc(n.title)}</strong><small>${esc(n.description||'')}</small></td><td><strong>${esc(t?.name||'—')}</strong><small>${esc(t?.area||'')}</small></td><td>${esc(s?.name||'—')}</td><td>${esc(p?.full_name||'—')}</td><td><span class="tri-sev ${n.severity}">${sev(n.severity)}</span></td><td><span class="tri-status ${n.status}">${st(n.status)}</span></td><td><b class="tri-rec">${rec.get(norm(n.title))||1}x</b></td><td><button class="btn light" data-nc="${n.id}">Detalhes</button></td></tr>`}).join('')}</tbody></table></div>`:'<div class="tri-empty"><strong>Nenhum resultado</strong><span>Altere os filtros para consultar outras inconformidades.</span></div>'}
function filtersHtml(d){const stores=[...new Map(d.ncs.map(n=>[n.store_id,d.m.s.get(n.store_id)]).filter(x=>x[1])).values()],cats=[...new Set(d.ncs.map(n=>{const e=d.m.e.get(n.execution_id);return d.m.t.get(e?.template_id)?.area||'Sem categoria'}))];return`<div class="tri-filters"><label><span>⌕</span><input id="triQ" value="${esc(filter.q)}" placeholder="Buscar inconformidade, checklist, loja ou colaborador"></label><select id="triCat"><option value="all">Todas as categorias</option>${cats.map(x=>`<option ${filter.cat===x?'selected':''}>${esc(x)}</option>`).join('')}</select><select id="triStore"><option value="all">Todas as lojas</option>${stores.map(x=>`<option value="${x.id}" ${filter.store===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select><select id="triSev"><option value="all">Todas as criticidades</option>${['critical','high','medium','low'].map(x=>`<option value="${x}" ${filter.sev===x?'selected':''}>${sev(x)}</option>`).join('')}</select><select id="triStatus"><option value="all">Todos os status</option>${[...new Set(d.ncs.map(x=>x.status))].map(x=>`<option value="${x}" ${filter.status===x?'selected':''}>${st(x)}</option>`).join('')}</select><button id="triClear" class="btn secondary">Limpar</button></div>`}
function renderDetailPanel(d){const sec=document.getElementById('analyze');if(!sec)return;let p=document.getElementById('triNcPanel');if(!p){p=document.createElement('div');p.id='triNcPanel';p.className='analysis-card tri-nc-panel';sec.querySelector('.analysis-lower')?.before(p)}const list=rows(d);p.innerHTML=`<div class="tri-panel-head"><div><div class="eyebrow">DRILL-DOWN</div><h2>Detalhamento das inconformidades</h2><p>Veja exatamente o que deu errado, onde aconteceu, quem executou e como está a tratativa.</p></div><strong>${list.length} resultado${list.length===1?'':'s'}</strong></div>${filtersHtml(d)}${tableHtml(list,d)}`;let timer;p.querySelector('#triQ')?.addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>{filter.q=e.target.value;renderDetailPanel(d)},180)});[['triCat','cat'],['triStore','store'],['triSev','sev'],['triStatus','status']].forEach(([id,k])=>p.querySelector('#'+id)?.addEventListener('change',e=>{filter[k]=e.target.value;renderDetailPanel(d)}));p.querySelector('#triClear').onclick=()=>{filter={q:'',cat:'all',store:'all',sev:'all',status:'all'};renderDetailPanel(d);renderCats(d)};p.querySelectorAll('[data-nc]').forEach(b=>b.onclick=()=>openNc(b.dataset.nc))}
async function enhanceAnalysis(){try{await load()}catch{return}const d=analysisData();renderKpis(d);chart(document.getElementById('analysisEvolution'),buckets(d,anDays));renderCats(d);renderIssues(d);renderDetailPanel(d);renderCorrect(d)}
function response(n,m){const r=m.r.get(n.response_id);if(!r)return n.description||'—';if(r.is_na)return'N/A';if(r.value_text!==null&&r.value_text!=='')return r.value_text;if(r.value_number!==null)return String(r.value_number).replace('.',',');if(r.value_boolean!==null)return r.value_boolean?'Sim':'Não';return n.description||'—'}
async function openNc(id){await load();const m=maps(),n=m.n.get(id);if(!n)return;const e=m.e.get(n.execution_id),t=m.t.get(e?.template_id),i=m.i.get(n.item_id),s=m.s.get(n.store_id),p=m.p.get(e?.performed_by),a=m.a.get(n.id),rp=m.p.get(a?.responsible_user_id),same=data.ncs.filter(x=>norm(x.title)===norm(n.title));document.getElementById('triNcModal')?.remove();const b=document.createElement('div');b.id='triNcModal';b.className='tri-modal-back';b.innerHTML=`<div class="tri-modal"><header><div><div class="eyebrow">NC-${n.id.split('-')[0].toUpperCase()}</div><h2>${esc(n.title)}</h2><p><span class="tri-sev ${n.severity}">${sev(n.severity)}</span> <span class="tri-status ${n.status}">${st(n.status)}</span> ${same.length>1?`<b class="tri-rec hot">${same.length}x recorrente</b>`:''}</p></div><button onclick="document.getElementById('triNcModal')?.remove()">×</button></header><main><div class="tri-answer"><span>Resposta registrada</span><strong>${esc(response(n,m))}</strong><small>${dt(n.opened_at)}</small></div><div class="tri-detail-grid"><div><span>Loja</span><strong>${esc(s?.name||'—')}</strong><small>${esc([s?.city,s?.state].filter(Boolean).join(' / '))}</small></div><div><span>Checklist</span><strong>${esc(t?.name||'—')}</strong><small>${esc(t?.area||'')}</small></div><div><span>Pergunta</span><strong>${esc(i?.title||n.title)}</strong><small>${esc(i?.instructions||'')}</small></div><div><span>Executado por</span><strong>${esc(p?.full_name||'—')}</strong><small>${esc(p?.job_title||p?.sector||'')}</small></div><div><span>Conformidade da execução</span><strong>${pct(e?.score)}</strong></div><div><span>Reincidência</span><strong>${same.length} ocorrência${same.length===1?'':'s'}</strong></div></div><section><h3>Plano de ação</h3>${a?`<div class="tri-action"><strong>${esc(a.action_text)}</strong><span>Status: <b>${st(a.status)}</b></span><span>Responsável: <b>${esc(rp?.full_name||'Não definido')}</b></span><span>Prazo: <b>${dt(a.due_at)}</b></span>${a.completed_at?`<span>Concluída: <b>${dt(a.completed_at)}</b></span>`:''}</div>`:'<p class="tri-inline-empty">Nenhum plano de ação vinculado.</p>'}</section><section><h3>Histórico</h3><div class="tri-history"><div><b>Inconformidade registrada</b><span>${dt(n.opened_at)}</span></div>${a?`<div><b>Plano de ação criado</b><span>${dt(a.created_at)}</span></div>`:''}${a?.completed_at?`<div><b>Ação concluída</b><span>${dt(a.completed_at)}</span></div>`:''}${n.resolved_at?`<div><b>NC resolvida</b><span>${dt(n.resolved_at)}</span></div>`:''}</div></section></main><footer><button class="btn secondary" onclick="document.getElementById('triNcModal')?.remove()">Fechar</button><button class="btn" id="triGoCorrect">Abrir gestão da NC</button></footer></div>`;document.body.appendChild(b);b.querySelector('#triGoCorrect').onclick=()=>{b.remove();navigate('correct');setTimeout(()=>renderCorrect(slice(3650,'all')),60)}}
function renderCorrect(d){const sec=document.getElementById('correct');if(!sec)return;let p=document.getElementById('triCorrectPanel');if(!p){p=document.createElement('div');p.id='triCorrectPanel';p.className='panel tri-correct';sec.appendChild(p)}p.innerHTML=`<div class="tri-panel-head"><div><div class="eyebrow">INCONFORMIDADES</div><h2>Ocorrências registradas</h2><p>Clique em Detalhes para abrir a ficha completa.</p></div><button class="btn secondary" id="triFullAnalysis">Análise completa →</button></div>${tableHtml(d.ncs.slice(0,12),d)}`;p.querySelectorAll('[data-nc]').forEach(b=>b.onclick=()=>openNc(b.dataset.nc));p.querySelector('#triFullAnalysis').onclick=()=>{navigate('analyze');setTimeout(enhanceAnalysis,60)}}
function openBucket(key,rows){const d=document.getElementById('analyze')?.classList.contains('active')?analysisData():slice(ovDays,selectedStore()),mode=(document.getElementById('analyze')?.classList.contains('active')?anDays:ovDays)<=14?'day':(document.getElementById('analyze')?.classList.contains('active')?anDays:ovDays)<=45?'week':'month',k=v=>{const x=new Date(v);if(mode==='day')return dk(x);if(mode==='month')return`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`;const z=new Date(x);z.setDate(z.getDate()-((z.getDay()+6)%7));return dk(z)},ncs=d.ncs.filter(n=>k(n.opened_at)===key);if(ncs.length===1)return openNc(ncs[0].id);if(ncs.length){filter.q='';navigate('analyze');setTimeout(()=>{enhanceAnalysis();document.getElementById('triNcPanel')?.scrollIntoView({behavior:'smooth'})},70)}}
function wire(){document.querySelectorAll('#overview .ov-periods button').forEach(b=>{if(b.dataset.tri)return;b.dataset.tri='1';b.addEventListener('click',()=>{ovDays=b.textContent.includes('90')?90:b.textContent.includes('30')?30:7;setTimeout(enhanceOverview,0)})});const u=document.getElementById('overviewUnit');if(u&&!u.dataset.tri){u.dataset.tri='1';u.addEventListener('change',enhanceOverview)}document.querySelectorAll('#analyze .analysis-filter').forEach(b=>{if(b.dataset.tri)return;const d=b.textContent.includes('90')?90:b.textContent.includes('30')?30:null;if(!d)return;b.dataset.tri='1';b.addEventListener('click',()=>{anDays=d;setTimeout(enhanceAnalysis,0)})})}
function wrap(){if(window.__triAnalytics)return;window.__triAnalytics=1;const ro=window.renderOverview;if(typeof ro==='function')window.renderOverview=function(){const r=ro.apply(this,arguments);setTimeout(enhanceOverview,0);return r};const ra=window.renderAnalysis;if(typeof ra==='function')window.renderAnalysis=function(){const r=ra.apply(this,arguments);setTimeout(enhanceAnalysis,0);return r};const nav=window.navigate;if(typeof nav==='function')window.navigate=function(){const r=nav.apply(this,arguments);setTimeout(()=>{wire();if(document.getElementById('overview')?.classList.contains('active'))enhanceOverview();if(document.getElementById('analyze')?.classList.contains('active'))enhanceAnalysis();if(document.getElementById('correct')?.classList.contains('active'))load().then(()=>renderCorrect(slice(3650,'all')))},60);return r}}
async function boot(){wrap();wire();try{await load(true)}catch{}if(document.getElementById('overview')?.classList.contains('active'))enhanceOverview();if(document.getElementById('analyze')?.classList.contains('active'))enhanceAnalysis()}
let tries=0,t=setInterval(()=>{tries++;if(O().ready&&DB()){clearInterval(t);boot()}else if(tries>60)clearInterval(t)},250);
})();