let state=JSON.parse(localStorage.getItem('trielaV4')||localStorage.getItem('trielaV3')||'null')||seed;state.trainingRuns=state.trainingRuns||[];state.trainingActions=state.trainingActions||[];state.ui=state.ui||{};state.ui.mode=state.ui.mode||'real';state.ui.previewRole=state.ui.previewRole||'admin';state.ui.tutorialDoneByRole=state.ui.tutorialDoneByRole||{};if(state.ui.tutorialDone===undefined)state.ui.tutorialDone=false;state.users=(state.users||[]).map((u,i)=>({...u,trainingStatus:u.trainingStatus||(i===0?'Liberado':'Em treinamento'),tutorialDone:u.tutorialDone??(i===0)}));function save(){localStorage.setItem('trielaV4',JSON.stringify(state));document.getElementById('cloudChip').textContent='☁ Salvo neste dispositivo';setTimeout(()=>document.getElementById('cloudChip').textContent='☁ Sincronizado neste dispositivo',1200)}function id(p){return p+Math.random().toString(36).slice(2,9)}function tpl(id){return state.templates.find(t=>t.id===id)}function avg(a){return a.length?a.reduce((s,v)=>s+v,0)/a.length:0}function metrics(){const completed=state.runs.filter(r=>r.status==='completed'),all=state.runs.filter(r=>r.status!=='canceled'),pending=state.actions.filter(a=>a.status!=='done'),overdue=state.actions.filter(a=>a.status==='overdue'),execution=all.length?completed.length/all.length*100:100,compliance=completed.length?avg(completed.map(r=>r.compliance)):100,correction=state.actions.length?(state.actions.filter(a=>a.status==='done').length/state.actions.length*100):100,punctuality=pending.length?((pending.length-overdue.length)/pending.length*100):100,score=execution*.30+compliance*.35+correction*.20+punctuality*.15;return{completed,all,pending,overdue,execution,compliance,correction,punctuality,score,nc:completed.reduce((s,r)=>s+(r.nc||0),0)}}function stat(label,value,detail){return `<div class="kpi"><div class="label">${label}</div><div class="value">${value}</div><div class="detail">${detail}</div></div>`}function renderOverview(){
 const m=metrics();
 const now=new Date(),hr=now.getHours(),greet=hr<12?'Bom dia':hr<18?'Boa tarde':'Boa noite';
 const days=['domingo','segunda-feira','terça-feira','quarta-feira','quinta-feira','sexta-feira','sábado'];
 const months=['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];
 const g=document.getElementById('overviewGreeting'),d=document.getElementById('overviewDate');if(g)g.textContent=`${greet}, André.`;if(d)d.textContent=`${days[now.getDay()]}, ${String(now.getDate()).padStart(2,'0')} de ${months[now.getMonth()]} • Veja o que precisa da sua atenção.`;
 const completed=m.completed.length,total=Math.max(m.all.length,completed),openNC=m.nc,overdue=m.overdue.length;
 const kpis=[
   {icon:'↗',c:'purple',trend:'↑ 4,2%',tc:'up',main:`${m.compliance.toFixed(1).replace('.',',')}%`,small:'meta 90%',label:'Conformidade geral',bar:Math.min(100,m.compliance),pc:'purple'},
   {icon:'✓',c:'teal',trend:`↑ ${completed}`,tc:'up',main:`${completed}`,small:`de ${total}`,label:'Checklists concluídos',bar:total?completed/total*100:0,pc:'teal'},
   {icon:'◷',c:'amber',trend:`↑ ${overdue}`,tc:'warn',main:`${overdue}`,small:'atividades',label:'Execuções atrasadas',bar:Math.min(100,overdue*22),pc:'amber'},
   {icon:'△',c:'red',trend:`${Math.min(openNC,3)} críticas`,tc:'warn',main:`${openNC}`,small:'abertas',label:'Não conformidades',bar:Math.min(100,openNC*10),pc:'red'}
 ];
 const ok=document.getElementById('overviewKpis');if(ok)ok.innerHTML=kpis.map(x=>`<div class="ov-kpi"><div class="ov-kpi-top"><div class="ov-icon ${x.c}">${x.icon}</div><span class="ov-trend ${x.tc}">${x.trend}</span></div><div class="ov-main"><strong>${x.main}</strong><small>${x.small}</small></div><div class="ov-label">${x.label}</div><div class="ov-progress ${x.pc}"><span style="width:${x.bar}%"></span></div></div>`).join('');
 const score=Math.round(m.score);const ps=document.getElementById('pulseScore');if(ps)ps.textContent=score;const ph=document.getElementById('pulseHealth');if(ph)ph.textContent=score>=85?'Saudável':score>=70?'Atenção':'Crítico';
 const pm=document.getElementById('pulseMetrics');if(pm)pm.innerHTML=[['Execução no prazo',m.punctuality,'p1'],['Conformidade',m.compliance,'p2'],['Ações resolvidas',m.correction,'p3']].map(([l,v,c])=>`<div class="pulse-row"><div class="pulse-top"><span>${l}</span><strong>${Math.round(v)}%</strong></div><div class="pulse-track"><span class="${c}" style="width:${Math.max(4,Math.min(100,v))}%"></span></div></div>`).join('');
 renderComplianceChart();renderOriginAndRecurrence();renderActivities();
}
function renderComplianceChart(){
 const completed=state.runs.filter(r=>r.status==='completed').slice().sort((a,b)=>new Date(a.date)-new Date(b.date));
 let vals=completed.slice(-7).map(r=>r.compliance);if(!vals.length)vals=[84,86,89,92,94,95,96];while(vals.length<7){vals.unshift(Math.max(70,(vals[0]||90)-2))}vals=vals.slice(-7);
 const labels=['Sex','Sáb','Dom','Seg','Ter','Qua','Hoje'],W=760,H=220,L=48,R=18,T=20,B=34,min=70,max=100;const x=i=>L+i*(W-L-R)/(vals.length-1),y=v=>T+(max-v)*(H-T-B)/(max-min);
 const pts=vals.map((v,i)=>`${x(i)},${y(v)}`).join(' ');const area=`${L},${H-B} ${pts} ${x(vals.length-1)},${H-B}`;const ticks=[70,80,90,100];const last=vals[vals.length-1],tx=Math.max(L,x(vals.length-1)-54),ty=Math.max(8,y(last)-48);
 const svg=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><defs><linearGradient id="ovAreaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#7567ff" stop-opacity=".22"/><stop offset="100%" stop-color="#7567ff" stop-opacity="0"/></linearGradient></defs><g class="chart-grid">${ticks.map(t=>`<line x1="${L}" x2="${W-R}" y1="${y(t)}" y2="${y(t)}"/>`).join('')}</g>${ticks.map(t=>`<text class="chart-label" x="6" y="${y(t)+3}">${t}%</text>`).join('')}<polygon class="chart-area" points="${area}"/><polyline class="chart-line" points="${pts}"/>${vals.map((v,i)=>`<circle class="chart-point ${i===vals.length-1?'chart-today':''}" cx="${x(i)}" cy="${y(v)}" r="4"/>`).join('')}${labels.map((l,i)=>`<text class="chart-label" text-anchor="middle" x="${x(i)}" y="${H-7}">${l}</text>`).join('')}<g class="chart-tooltip"><rect x="${tx}" y="${ty}" width="48" height="35"/><text x="${tx+24}" y="${ty+14}" text-anchor="middle">${last}%</text><text x="${tx+24}" y="${ty+27}" text-anchor="middle" style="font-size:7px;font-weight:500">Hoje</text></g></svg>`;
 const el=document.getElementById('complianceChart');if(el)el.innerHTML=svg;
}
function renderOriginAndRecurrence(){
 const map={};state.runs.filter(r=>r.status==='completed').forEach(r=>{const t=tpl(r.templateId);const k=t?.category||'Operações';map[k]=(map[k]||0)+(r.nc||0)});let origins=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,4);if(!origins.length)origins=[['Segurança',12],['Qualidade',9],['Operações',6],['Manutenção',4]];const max=Math.max(1,...origins.map(x=>x[1]));const ol=document.getElementById('originList');if(ol)ol.innerHTML=origins.map(([n,v],i)=>`<div class="origin-row"><span>${n}</span><div class="origin-track"><span class="c${i+1}" style="width:${Math.max(12,v/max*100)}%"></span></div><strong>${v}</strong></div>`).join('');
 const bad=[];state.runs.filter(r=>r.status==='completed').forEach(r=>{const t=tpl(r.templateId);(r.answers||[]).filter(a=>a.ok===false).forEach(a=>{const q=t?.questions?.find(q=>q.id===a.qid);if(q)bad.push(q.title)})});const counts={};bad.forEach(x=>counts[x]=(counts[x]||0)+1);let rec=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,3);if(!rec.length)rec=[['Rotas obstruídas',4],['Temperatura fora do limite',3],['Registro incompleto',2]];const colors=['#ef5368','#f2a62e','#3196ed'];const rl=document.getElementById('recurrenceList');if(rl)rl.innerHTML=rec.map(([n,v],i)=>`<div class="recurrence-item"><span class="recurrence-dot" style="background:${colors[i]}"></span><span>${n}</span><strong>${v}x</strong></div>`).join('');
}
function renderActivities(){
 const templates=state.templates.slice(0,4);const times=['08:00','09:30','11:00','18:00'];const names=templates.length?templates.map(t=>t.name):['Inspeção de abertura','Controle de temperatura','Auditoria de organização','Fechamento de turno'];const el=document.getElementById('activityList');if(el)el.innerHTML=names.slice(0,4).map((n,i)=>`<div class="activity-row"><div class="activity-time">${times[i]}</div><div><div class="activity-title">${n}</div><div class="activity-unit">${i===2?'Estoque · ':''}Unidade Centro</div></div><span class="activity-status ${i<2?'running':'pending'}">● ${i<2?'Em andamento':'Pendente'}</span></div>`).join('');
}
