/* Triela Checklists — evidências e observações robustas por item */
(function(){
'use strict';
const O=()=>window.TRIELA_OFFICIAL||{};
const notify=m=>typeof window.toast==='function'?window.toast(m):alert(m);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let ctx=null,wrapped=false;
async function rulesFor(tid){const sb=O().supabase;if(!sb)return new Map();const q=await sb.from('cp_template_items').select('id,allows_notes,requires_note_on_no,requires_photo,requires_photo_on_no,max_photos').eq('template_id',tid).is('archived_at',null);if(q.error)throw q.error;return new Map((q.data||[]).map(x=>[x.id,x]));}
function injectExtras(t,rules){
 const cards=[...document.querySelectorAll('#answersBody .answer')];ctx={template:t,rules,startedAt:new Date().toISOString(),extra:{}};
 t.questions.forEach((q,i)=>{const card=cards[i];if(!card||card.querySelector('.robust-extra'))return;const r=rules.get(q.id)||{},max=Math.max(1,Math.min(10,Number(r.max_photos)||3));ctx.extra[q.id]={max,allowsNotes:r.allows_notes!==false,noteOnNo:r.requires_note_on_no===true,photoAlways:r.requires_photo===true,photoOnNo:r.requires_photo_on_no===true};const box=document.createElement('div');box.className='robust-extra';box.dataset.robustQ=q.id;box.innerHTML=`<div class="robust-extra-badges"><span>${r.requires_note_on_no?'Observação obrigatória se NC':'Observação opcional'}</span><span>${r.requires_photo?'Foto obrigatória':r.requires_photo_on_no?'Foto obrigatória se NC':'Foto opcional'}</span><span>Até ${max} fotos</span></div>${r.allows_notes===false?'':`<label><b>Observação do item</b><textarea class="input" data-robust-note="${q.id}" placeholder="Descreva o que encontrou ou detalhe a situação..."></textarea></label>`}<label class="robust-photo"><b>📷 Fotos / evidências</b><small>Registre no momento da execução quando necessário.</small><input type="file" data-robust-photo="${q.id}" accept="image/*" capture="environment" multiple></label>`;card.appendChild(box);const input=box.querySelector('[data-robust-photo]');input?.addEventListener('change',()=>{if(input.files.length>max){notify(`Máximo de ${max} fotos neste item.`);input.value='';}});});
}
function findFirstIssue(t,answers){if(!ctx)return null;for(let i=0;i<t.questions.length;i++){const q=t.questions[i],r=ctx.extra[q.id]||{},a=answers?.[q.id],bad=a?.ok===false,notes=document.querySelector(`[data-robust-note='${q.id}']`)?.value.trim()||'',files=document.querySelector(`[data-robust-photo='${q.id}']`)?.files||[];if(bad&&r.noteOnNo&&!notes)return {i,msg:'adicione uma observação nesta não conformidade'};if((r.photoAlways||(bad&&r.photoOnNo))&&!files.length)return {i,msg:'adicione a foto obrigatória deste item'};if(files.length>(r.max||3))return {i,msg:`o limite é de ${r.max||3} fotos neste item`};}return null;}
function go(i){const cards=[...document.querySelectorAll('#runModal .mobile-run-answer,#answersBody .answer')],target=cards[i];if(!target)return;const active=cards.findIndex(x=>x.classList.contains('mobile-step-active'));if(active>=0){const diff=i-active,btn=diff>0?document.querySelector('.mobile-run-next'):document.querySelector('.mobile-run-prev');for(let n=0;n<Math.abs(diff);n++)btn?.click();}setTimeout(()=>target.scrollIntoView({behavior:'smooth',block:'center'}),50);}
async function saveExtras(t){
 if(!ctx||!O().supabase||!O().profile||!O().user)return;const sb=O().supabase,p=O().profile,u=O().user;
 const ex=await sb.from('cp_executions').select('id,created_at').eq('template_id',t.id).eq('performed_by',u.id).gte('created_at',ctx.startedAt).order('created_at',{ascending:false}).limit(1).maybeSingle();if(ex.error||!ex.data)return;
 const rs=await sb.from('cp_responses').select('id,item_id').eq('execution_id',ex.data.id);if(rs.error)throw rs.error;const by=Object.fromEntries((rs.data||[]).map(x=>[x.item_id,x.id]));let photos=0;
 for(const q of t.questions){const rid=by[q.id],note=document.querySelector(`[data-robust-note='${q.id}']`)?.value.trim()||'',input=document.querySelector(`[data-robust-photo='${q.id}']`),files=[...(input?.files||[])];if(rid&&note){const up=await sb.from('cp_responses').update({notes:note}).eq('id',rid);if(up.error)throw up.error;await sb.from('cp_nonconformities').update({description:`Observação: ${note}`}).eq('execution_id',ex.data.id).eq('item_id',q.id).neq('status','resolved');}
  for(const file of files){const clean=(file.name||'foto.jpg').replace(/[^a-zA-Z0-9._-]+/g,'_'),id=crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random().toString(16).slice(2),path=`${p.organization_id}/${ex.data.id}/${rid||q.id}/${id}-${clean}`;const st=await sb.storage.from('cp-evidence').upload(path,file,{contentType:file.type||'image/jpeg',upsert:false});if(st.error)throw st.error;const ev=await sb.from('cp_evidence').insert({organization_id:p.organization_id,execution_id:ex.data.id,response_id:rid||null,environment:window.state?.ui?.mode==='training'?'training':'production',storage_path:path,file_name:file.name||clean,mime_type:file.type||null,size_bytes:file.size||null,caption:note||null,captured_by:u.id,captured_at:new Date().toISOString()});if(ev.error)throw ev.error;photos++;}}
 if(photos)notify(`${photos} foto${photos===1?'':'s'} salva${photos===1?'':'s'} como evidência.`);
}
function wrapRun(){if(wrapped||typeof window.startRun!=='function'||typeof window.finishRun!=='function')return;wrapped=true;const oldStart=window.startRun,oldFinish=window.finishRun;window.startRun=async function(tid){const t=window.state?.templates?.find(x=>x.id===tid),rules=t?await rulesFor(tid):new Map(),out=await oldStart.apply(this,arguments);setTimeout(()=>t&&injectExtras(t,rules),80);return out;};window.startScheduledRun=function(tid){return window.startRun(tid);};window.finishRun=async function(t,answers){const issue=findFirstIssue(t,answers);if(issue){notify(`Antes de finalizar, ${issue.msg}.`);go(issue.i);const b=document.getElementById('finishBtn');if(b){b.disabled=false;b.textContent='Finalizar checklist';}return;}const snapshot=ctx?{...ctx,extra:{...ctx.extra}}:null,out=await oldFinish.apply(this,arguments);try{if(snapshot){ctx=snapshot;await saveExtras(t);}}catch(e){notify(`Checklist salvo, mas houve falha ao salvar evidências: ${e.message||e}`);}finally{ctx=null;}return out;};}
function injectBuilder(){const qr=document.getElementById('qRule');if(!qr||document.getElementById('robustBuilderRules'))return;const box=document.createElement('div');box.id='robustBuilderRules';box.className='robust-builder-rules';box.innerHTML=`<strong>Regras do item</strong><label><input id="qAllowsNotes" type="checkbox" checked> Permitir observação</label><label><input id="qNoteOnNo" type="checkbox"> Exigir observação se reprovar</label><label><input id="qPhotoAlways" type="checkbox"> Exigir foto sempre</label><label><input id="qPhotoOnNo" type="checkbox"> Exigir foto se reprovar</label><label>Máx. fotos <select class="input" id="qMaxPhotos"><option>1</option><option selected>3</option><option>5</option><option>10</option></select></label>`;qr.closest('.formrow')?.insertAdjacentElement('afterend',box);const list=document.getElementById('questionList');if(list){const ed=document.createElement('div');ed.className='robust-rule-editor';ed.innerHTML=`<strong>Configurar pergunta existente</strong><select class="input" id="robustItemSelect"></select><div><label><input id="eNotes" type="checkbox"> Observação</label><label><input id="eNoteNo" type="checkbox"> Observação se NC</label><label><input id="ePhoto" type="checkbox"> Foto sempre</label><label><input id="ePhotoNo" type="checkbox"> Foto se NC</label><select class="input" id="eMax"><option>1</option><option>3</option><option>5</option><option>10</option></select></div><button class="btn secondary" id="robustLoad">Carregar</button><button class="btn" id="robustSave">Salvar regras</button>`;list.insertAdjacentElement('afterend',ed);document.getElementById('robustLoad').onclick=loadEdit;document.getElementById('robustSave').onclick=saveEdit;}refreshSelect();}
function refreshSelect(){const s=document.getElementById('robustItemSelect'),tid=document.getElementById('builderTemplate')?.value,t=window.state?.templates?.find(x=>x.id===tid);if(s)s.innerHTML=(t?.questions||[]).map((q,i)=>`<option value="${q.id}">${i+1}. ${esc(q.title)}</option>`).join('');}
async function loadEdit(){const id=document.getElementById('robustItemSelect')?.value;if(!id)return;const q=await O().supabase.from('cp_template_items').select('allows_notes,requires_note_on_no,requires_photo,requires_photo_on_no,max_photos').eq('id',id).single();if(q.error)return notify(q.error.message);eNotes.checked=q.data.allows_notes!==false;eNoteNo.checked=q.data.requires_note_on_no===true;ePhoto.checked=q.data.requires_photo===true;ePhotoNo.checked=q.data.requires_photo_on_no===true;eMax.value=String(q.data.max_photos||3);}
async function saveEdit(){const id=document.getElementById('robustItemSelect')?.value;if(!id)return;const q=await O().supabase.from('cp_template_items').update({allows_notes:eNotes.checked,requires_note_on_no:eNoteNo.checked,requires_photo:ePhoto.checked,requires_photo_on_no:ePhotoNo.checked,max_photos:Number(eMax.value)||3}).eq('id',id);notify(q.error?q.error.message:'Regras atualizadas.');}
function wrapAdd(){if(typeof window.addQuestion!=='function'||window.addQuestion.__robust)return;const old=window.addQuestion;window.addQuestion=async function(){const before=Date.now(),out=await old.apply(this,arguments);setTimeout(async()=>{try{const sb=O().supabase,tid=document.getElementById('builderTemplate')?.value;if(!sb||!tid)return;const q=await sb.from('cp_template_items').select('id,created_at').eq('template_id',tid).gte('created_at',new Date(before-1000).toISOString()).order('created_at',{ascending:false}).limit(1).maybeSingle();if(q.data?.id)await sb.from('cp_template_items').update({allows_notes:document.getElementById('qAllowsNotes')?.checked!==false,requires_note_on_no:document.getElementById('qNoteOnNo')?.checked===true,requires_photo:document.getElementById('qPhotoAlways')?.checked===true,requires_photo_on_no:document.getElementById('qPhotoOnNo')?.checked===true,max_photos:Number(document.getElementById('qMaxPhotos')?.value)||3}).eq('id',q.data.id);refreshSelect();}catch(e){}},700);return out;};window.addQuestion.__robust=true;}
function boot(){wrapRun();injectBuilder();wrapAdd();const bt=document.getElementById('builderTemplate');if(bt&&!bt.dataset.robust){bt.dataset.robust='1';bt.addEventListener('change',()=>setTimeout(refreshSelect,60));}[500,1500,3200].forEach(ms=>setTimeout(()=>{wrapRun();injectBuilder();wrapAdd();},ms));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
