/* Triela Checklists — persistência confiável das evidências robustas */
(function(){
'use strict';
const O=()=>window.TRIELA_OFFICIAL||{};
const notify=m=>typeof window.toast==='function'?window.toast(m):alert(m);
let done=false;
function capture(t){const data={};(t?.questions||[]).forEach(q=>{data[q.id]={note:document.querySelector(`[data-robust-note='${q.id}']`)?.value.trim()||'',files:[...(document.querySelector(`[data-robust-photo='${q.id}']`)?.files||[])]};});return data;}
async function persist(t,data,from){const sb=O().supabase,p=O().profile,u=O().user;if(!sb||!p||!u)return;const ex=await sb.from('cp_executions').select('id,created_at').eq('template_id',t.id).eq('performed_by',u.id).gte('created_at',from).order('created_at',{ascending:false}).limit(1).maybeSingle();if(ex.error||!ex.data)return;const rs=await sb.from('cp_responses').select('id,item_id').eq('execution_id',ex.data.id);if(rs.error)throw rs.error;const by=Object.fromEntries((rs.data||[]).map(x=>[x.item_id,x.id]));let photos=0;for(const q of t.questions||[]){const d=data[q.id]||{},rid=by[q.id];if(rid&&d.note){const r=await sb.from('cp_responses').update({notes:d.note}).eq('id',rid);if(r.error)throw r.error;await sb.from('cp_nonconformities').update({description:`Observação: ${d.note}`}).eq('execution_id',ex.data.id).eq('item_id',q.id).neq('status','resolved');}for(const file of d.files||[]){const exists=await sb.from('cp_evidence').select('id').eq('execution_id',ex.data.id).eq('response_id',rid).eq('file_name',file.name||'foto.jpg').limit(1);if(exists.data?.length)continue;const clean=(file.name||'foto.jpg').replace(/[^a-zA-Z0-9._-]+/g,'_'),uid=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`,path=`${p.organization_id}/${ex.data.id}/${rid||q.id}/${uid}-${clean}`,up=await sb.storage.from('cp-evidence').upload(path,file,{contentType:file.type||'image/jpeg',upsert:false});if(up.error)throw up.error;const ev=await sb.from('cp_evidence').insert({organization_id:p.organization_id,execution_id:ex.data.id,response_id:rid||null,environment:window.state?.ui?.mode==='training'?'training':'production',storage_path:path,file_name:file.name||clean,mime_type:file.type||null,size_bytes:file.size||null,caption:d.note||null,captured_by:u.id,captured_at:new Date().toISOString()});if(ev.error)throw ev.error;photos++;}}if(photos)notify(`${photos} evidência${photos===1?'':'s'} fotográfica${photos===1?'':'s'} salva${photos===1?'':'s'}.`);}
function wrap(){if(done||typeof window.finishRun!=='function')return;done=true;const old=window.finishRun;window.finishRun=async function(t,answers){const data=capture(t),from=new Date(Date.now()-3000).toISOString(),out=await old.apply(this,arguments);if(document.getElementById('runModal'))return out;try{await persist(t,data,from);}catch(e){notify(`Checklist finalizado, mas a evidência não foi totalmente salva: ${e.message||e}`);}return out;};window.finishRun.__trielaEvidencePersist=true;}
function boot(){wrap();[500,1500,3200].forEach(ms=>setTimeout(wrap,ms));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
