let routineTab='today', analysisPeriod='30d';
function setRoutineTab(tab,btn){routineTab=tab;document.querySelectorAll('.routine-tabs button').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');renderRoutine()}
function renderRoutine(){
 const templates=state.templates||[];const demoNames=['Inspeção de abertura','Controle de temperatura','Auditoria de organização','Fechamento de turno','Verificação de equipamentos'];const names=templates.length?templates.slice(0,5).map(t=>t.name):demoNames;while(names.length<5)names.push(demoNames[names.length]);const times=['08:00','09:30','11:00','18:00','07:20'];const mins=[8,4,12,6,5];const states=['continue','continue','pending','pending','done'];
 const nextTpl=templates[0];const nn=document.getElementById('routineNextName');if(nn)nn.textContent=names[0];const nq=document.getElementById('routineQuestions');if(nq)nq.textContent=nextTpl?.questions?.length||5;const rb=document.getElementById('routineStartBtn');if(rb)rb.onclick=()=>nextTpl?startRun(nextTpl.id):openQuickRun();
 const done=18,pending=4,late=2,pct=Math.round(done/(done+pending+late)*100);const donut=document.getElementById('routineDonut');if(donut)donut.style.setProperty('--p',pct+'%');['routinePct','routineDone','routinePending','routineLate'].forEach((id,i)=>{const el=document.getElementById(id);if(el)el.textContent=[pct+'%',done,pending,late][i]});
 const tips=['Registre a evidência no momento da execução. Isso reduz retrabalho e melhora a rastreabilidade.','Leia a instrução da pergunta antes de responder. Uma evidência bem registrada facilita a validação.','Se encontrar um desvio crítico, registre imediatamente e não espere o fim do turno.'];const tip=document.getElementById('routineTip');if(tip)tip.textContent=tips[new Date().getDate()%tips.length];
 let idx=[0,1,2,3,4];if(routineTab==='next')idx=[2,3];if(routineTab==='done')idx=[4];const list=document.getElementById('routineList');if(list)list.innerHTML=idx.map(i=>{const st=states[i],t=templates[i];const label=st==='done'?'Concluído':st==='continue'?'Continuar':'Executar';const cls=i===1?'amber':i===4?'green':'';const pri=i===2?'priority-high':i===3?'priority-medium':'priority-low';return `<div class="routine-row"><div class="routine-row-icon ${cls}">▣</div><div><strong>${names[i]}</strong><small><span class="priority-dot ${pri}"></span>Unidade Centro • ${mins[i]} min${i<2?' • evidência obrigatória':''}</small></div><div class="routine-row-time">${times[i]}${i===0?'<br><span style="color:#e55067">em andamento</span>':''}</div>${st==='done'?'<span class="status ok">● Concluído</span>':`<button class="btn ${st==='pending'?'secondary':''}" onclick="${t?`startRun('${t.id}')`:'openQuickRun()'}">${label}</button>`}</div>`}).join('');
}
function setAnalysisPeriod(p,btn){analysisPeriod=p;document.querySelectorAll('.analysis-filter').forEach(b=>b.classList.remove('active'));if(btn){btn.classList.add('active');btn.style.borderColor='#9c8fff';btn.style.color='#5d50e9'}renderAnalysis()}
function analysisIssueData(){const counts={};state.runs.filter(r=>r.status==='completed').forEach(r=>{const t=tpl(r.templateId);(r.answers||[]).filter(a=>a.ok===false).forEach(a=>{const q=t?.questions?.find(x=>x.id===a.qid);if(!q)return;const k=q.title;counts[k]=counts[k]||{name:k,count:0,category:t?.category||'Operações',critical:q.critical||'medium'};counts[k].count++})});let arr=Object.values(counts).sort((a,b)=>b.count-a.count);if(arr.length<5)arr=arr.concat([{name:'Produto fora de validade',count:18,category:'Qualidade',critical:'critical'},{name:'Temperatura fora do padrão',count:15,category:'Operações',critical:'critical'},{name:'Acesso obstruído',count:12,category:'Segurança',critical:'critical'},{name:'Evidência incompleta',count:9,category:'Qualidade',critical:'high'},{name:'Organização fora do padrão',count:7,category:'Operações',critical:'medium'}]);return arr.slice(0,5)}
function renderAnalysis(){
 const m=metrics(),issues=analysisIssueData(),crit=issues.filter(x=>['critical','high'].includes(x.critical)).reduce((s,x)=>s+x.count,0);const k=document.getElementById('analysisPremiumKpis');if(k)k.innerHTML=[{l:'Conformidade geral',v:`${m.compliance.toFixed(1).replace('.',',')}%`,i:'↗',bg:'#eeeaff',c:'#6757f2',tr:'↑ 4,2% vs. anterior'},{l:'Total de NC',v:m.nc||42,i:'!',bg:'#fff4df',c:'#d88a00',tr:'↓ 8% vs. anterior'},{l:'NC críticas',v:crit||8,i:'△',bg:'#ffecef',c:'#e24b63',tr:'↑ 2 vs. anterior',bad:true},{l:'Tempo médio resolução',v:'2,4',small:'dias',i:'◷',bg:'#e5f9f4',c:'#14a98f',tr:'↓ 0,3d vs. anterior'}].map(x=>`<div class="analysis-kpi"><div class="ak-top"><span class="ak-label">${x.l}</span><span class="ak-icon" style="background:${x.bg};color:${x.c}">${x.i}</span></div><div class="ak-value">${x.v}${x.small?` <small>${x.small}</small>`:''}</div><div class="ak-trend ${x.bad?'bad':''}">${x.tr}</div></div>`).join('');
 const vals=[86.5,88.9,88.1,91.3,Math.max(91.8,m.compliance)],labs=['Mai','Jun','Jul','Ago','Set'],W=710,H=190,L=36,R=14,T=14,B=28,min=84,max=94,x=i=>L+i*(W-L-R)/(vals.length-1),y=v=>T+(max-v)*(H-T-B)/(max-min);const pts=vals.map((v,i)=>`${x(i)},${y(v)}`).join(' '),area=`${L},${H-B} ${pts} ${x(vals.length-1)},${H-B}`,ticks=[85,87.5,90,92.5];const lx=x(vals.length-1)-23,ly=y(vals.at(-1))-33;const svg=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><defs><linearGradient id="analysisGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#665af3" stop-opacity=".18"/><stop offset="100%" stop-color="#665af3" stop-opacity="0"/></linearGradient></defs>${ticks.map(t=>`<line class="analysis-gridline" x1="${L}" x2="${W-R}" y1="${y(t)}" y2="${y(t)}"/><text class="analysis-label" x="0" y="${y(t)+3}">${String(t).replace('.',',')}%</text>`).join('')}<polygon class="analysis-fill" points="${area}"/><polyline class="analysis-poly" points="${pts}"/>${vals.map((v,i)=>`<circle class="analysis-point" cx="${x(i)}" cy="${y(v)}" r="4"/>`).join('')}${labs.map((l,i)=>`<text class="analysis-label" text-anchor="middle" x="${x(i)}" y="${H-6}">${l}</text>`).join('')}<g class="analysis-tooltip"><rect x="${lx}" y="${ly}" width="46" height="28"/><text x="${lx+23}" y="${ly+12}" text-anchor="middle">${vals.at(-1).toFixed(1).replace('.',',')}%</text><text x="${lx+23}" y="${ly+22}" text-anchor="middle" style="font-size:6px;font-weight:500">Setembro</text></g></svg>`;const ch=document.getElementById('analysisEvolution');if(ch)ch.innerHTML=svg;
 const cmap={};state.runs.filter(r=>r.status==='completed').forEach(r=>{const c=tpl(r.templateId)?.category||'Operações';cmap[c]=(cmap[c]||0)+(r.nc||0)});let cats=Object.entries(cmap).sort((a,b)=>b[1]-a[1]).slice(0,4);if(cats.length<4)cats=[['Segurança',32],['Qualidade',28],['Operações',22],['Manutenção',18]];const maxCat=Math.max(...cats.map(x=>x[1]),1),colors=['#7768f4','#2dbda8','#f2aa32','#e96377'];const ce=document.getElementById('analysisCategories');if(ce)ce.innerHTML=cats.map(([n,v],i)=>`<div class="cat-row"><span>${n}</span><div class="cat-track"><span style="width:${Math.max(8,v/maxCat*100)}%;background:${colors[i]}"></span></div><strong>${v}</strong></div>`).join('');
 const ti=document.getElementById('analysisTopIssues');if(ti)ti.innerHTML=issues.map(x=>`<div class="nc-row"><strong>${x.name}</strong><span>${x.category}</span><span><span class="crit-pill ${x.critical==='high'?'high':''}">${x.critical==='critical'?'Crítica':x.critical==='high'?'Alta':x.critical==='medium'?'Média':'Baixa'}</span></span><strong>${x.count}</strong></div>`).join('');const rec=issues.filter(x=>x.count>=2).slice(0,3);const re=document.getElementById('analysisRecurrences');if(re)re.innerHTML=rec.map((x,i)=>`<div class="rec-card-item"><span class="dot" style="background:${['#e84e65','#f2a62e','#2d9bf0'][i]}"></span><div><strong>${x.name}</strong><small>${x.category} • ${x.count} ocorrências no período</small></div><b>${Math.max(2,Math.round(x.count/4))}x</b></div>`).join('')+`<button class="btn secondary" style="margin-top:10px;width:100%">Analisar causas →</button>`;
}
function setPreviewRole(role){state.ui.previewRole=role;save();applyRoleView();const target=role==='collaborator'?'routine':'overview';navigate(target);toast(role==='admin'?'Visualização: Administrador':role==='manager'?'Visualização: Gestor/Líder':'Visualização: Colaborador')}
function applyRoleView(){const role=state.ui.previewRole||'admin',sel=document.getElementById('previewRole');if(sel)sel.value=role;const allowed={admin:['overview','routine','execute','correct','analyze','models','builder','training','help','users','settings'],manager:['overview','routine','execute','correct','analyze','training','help'],collaborator:['routine','execute','training','help']}[role];document.querySelectorAll('.navbtn[data-page]').forEach(b=>b.classList.toggle('hidden-by-role',!allowed.includes(b.dataset.page)));const active=document.querySelector('.section.active')?.id;if(active&&!allowed.includes(active))navigate(role==='collaborator'?'routine':'overview');const prof=document.querySelector('.profile small');if(prof){const env=state.ui.mode==='training'?'Modo treinamento':'Operação real';prof.innerHTML=`${role==='admin'?'Administrador':role==='manager'?'Gestor/Líder':'Colaborador'} · <span id="profileEnvironment">${env}</span>`}}