const tutorials={
admin:[
 {page:'overview',title:'Visão geral do administrador',text:'Aqui você acompanha a saúde da operação inteira: conformidade, atrasos, não conformidades, reincidências e próximas atividades.',bullets:['Use o filtro de unidade para mudar o recorte.','O Pulso Operacional resume execução, conformidade, ações e prazo.']},
 {page:'users',title:'Estrutura, usuários e permissões',text:'O administrador define quem entra no sistema e o que cada perfil pode fazer.',bullets:['Administrador: configura tudo.','Gestor/Líder: acompanha, trata e valida.','Colaborador: executa sua rotina de forma simples.']},
 {page:'models',title:'Biblioteca de modelos',text:'Você pode começar com modelos prontos e adaptar tudo à realidade da empresa.'},
 {page:'builder',title:'Construtor universal de checklist',text:'Crie perguntas, criticidade, evidências e regras para transformar qualquer rotina em checklist.',bullets:['Perguntas podem gerar ações automaticamente.','O sistema foi pensado para diferentes segmentos e unidades.']},
 {page:'routine',title:'Experiência do colaborador',text:'Minha Rotina organiza o dia do colaborador por horário, prioridade e status. O administrador pode visualizar essa experiência usando o seletor de perfil.'},
 {page:'execute',title:'Execução e evidências',text:'Durante a execução, o usuário responde perguntas, registra fotos/evidências e finaliza o checklist.'},
 {page:'correct',title:'Não conformidades e planos de ação',text:'Toda reprovação relevante pode virar uma tratativa com responsável e prazo, fechando o ciclo de gestão.'},
 {page:'analyze',title:'Análises e tomada de decisão',text:'A área de análises mostra evolução, categorias de desvio, criticidade e reincidências para apoiar decisões.'},
 {page:'training',title:'Modo Treinamento',text:'Novos usuários podem praticar sem alterar indicadores oficiais, rankings ou relatórios da operação real.'},
 {page:'help',title:'Centro de Ajuda',text:'Todo tutorial pode ser refeito. O sistema também terá ajuda por processo e por tela.'},
 {page:'settings',title:'Configurações e regras',text:'Aqui ficam regras gerais, automações, parâmetros e pesos dos indicadores. Fim do tour do Administrador.'}
],
manager:[
 {page:'overview',title:'Visão geral do Gestor/Líder',text:'Comece olhando conformidade, atrasos, NC e prioridades da sua área.'},
 {page:'routine',title:'Rotina da equipe',text:'Veja como os colaboradores recebem suas atividades e acompanhe o andamento do dia.'},
 {page:'execute',title:'Execuções',text:'Consulte e execute checklists permitidos para sua unidade ou setor.'},
 {page:'correct',title:'Tratativas',text:'Acompanhe não conformidades, defina responsáveis, cobre prazos e valide correções.'},
 {page:'analyze',title:'Análises',text:'Use filtros e tendências para descobrir onde a operação está melhorando ou piorando.',bullets:['Veja reincidências antes que se tornem crônicas.','Compare categorias e criticidades.']},
 {page:'training',title:'Treinamento da equipe',text:'Acompanhe quem está em treinamento e pratique processos sem misturar dados reais.'},
 {page:'help',title:'Ajuda e reciclagem',text:'Reabra este tutorial sempre que precisar treinar ou reciclar o uso do sistema.'}
],
collaborator:[
 {page:'routine',title:'Sua tela principal: Minha Rotina',text:'Aqui você vê exatamente o que precisa fazer hoje. A próxima atividade fica em destaque.'},
 {page:'routine',title:'Prioridade, horário e progresso',text:'Cada atividade mostra horário, duração, prioridade e status. O progresso indica quanto do dia já foi concluído.'},
 {page:'execute',title:'Iniciar um checklist',text:'Toque em Iniciar/Continuar, responda as perguntas e siga as orientações exibidas.'},
 {page:'execute',title:'Registrar evidências',text:'Quando solicitado, anexe foto ou evidência no momento da execução para garantir rastreabilidade.'},
 {page:'correct',title:'Quando houver um problema',text:'Uma resposta não conforme pode abrir uma tratativa automaticamente. Você não precisa criar controles paralelos.'},
 {page:'training',title:'Treinar sem medo',text:'No Modo Treinamento você pode praticar todos esses passos sem afetar os dados oficiais.'},
 {page:'help',title:'Sempre existe ajuda',text:'Você pode rever o tutorial e consultar explicações sempre que tiver dúvida. Fim do tour do Colaborador.'}
]};
let tutorialIndex=0,tutorialRole='admin';function showTutorial(force=false,role=null){tutorialRole=role||state.ui.previewRole||'admin';state.ui.tutorialDoneByRole=state.ui.tutorialDoneByRole||{};if(state.ui.tutorialDoneByRole[tutorialRole]&&!force)return;tutorialIndex=0;renderTutorial()}function renderTutorial(){const arr=tutorials[tutorialRole],step=arr[tutorialIndex],pct=Math.round((tutorialIndex+1)/arr.length*100);if(step.page)navigate(step.page);const root=document.getElementById('modalRoot');root.innerHTML=`<div class="modalback"><div class="modal" style="max-width:650px"><div class="modalhead"><div><div class="eyebrow">Primeiro acesso</div><h2 style="margin:4px 0;color:var(--navy)">Tutorial completo por perfil</h2><div class="tutorial-role-picker"><button class="${tutorialRole==='admin'?'active':''}" onclick="changeTutorialRole('admin')">Administrador</button><button class="${tutorialRole==='manager'?'active':''}" onclick="changeTutorialRole('manager')">Gestor/Líder</button><button class="${tutorialRole==='collaborator'?'active':''}" onclick="changeTutorialRole('collaborator')">Colaborador</button></div></div><button class="iconbtn" onclick="finishTutorial()">×</button></div><div class="modalbody"><div class="tutorial-progress"><span style="width:${pct}%"></span></div><div class="tutorial-step"><div class="stepnum">Passo ${tutorialIndex+1} de ${arr.length}</div><h2>${step.title}</h2><p>${step.text}</p>${step.bullets?`<ul>${step.bullets.map(x=>`<li>${x}</li>`).join('')}</ul>`:''}<span class="tutorial-page-pill">Tela demonstrada: ${pageLabel(step.page)}</span><div class="tutorial-tip">O tutorial muda a tela ao fundo automaticamente para mostrar onde cada função fica.</div></div></div><div class="modalfooter"><button class="btn secondary" onclick="finishTutorial()">Pular</button>${tutorialIndex>0?'<button class="btn secondary" onclick="tutorialPrev()">Voltar</button>':''}<button class="btn" onclick="tutorialNext()">${tutorialIndex===arr.length-1?'Concluir':'Próximo'}</button></div></div></div>`}function pageLabel(p){return({overview:'Visão geral',routine:'Minha rotina',execute:'Checklists',correct:'Não conformidades',analyze:'Análises',models:'Modelos',builder:'Construtor',training:'Treinamento',help:'Centro de Ajuda',users:'Equipe e acessos',settings:'Configurações'})[p]||p}function changeTutorialRole(role){tutorialRole=role;tutorialIndex=0;renderTutorial()}function tutorialNext(){const arr=tutorials[tutorialRole];if(tutorialIndex<arr.length-1){tutorialIndex++;renderTutorial()}else finishTutorial()}function tutorialPrev(){if(tutorialIndex>0){tutorialIndex--;renderTutorial()}}function finishTutorial(){state.ui.tutorialDone=true;state.ui.tutorialDoneByRole=state.ui.tutorialDoneByRole||{};state.ui.tutorialDoneByRole[tutorialRole]=true;save();closeModal();applyRoleView();toast('Tutorial concluído. Você pode revê-lo no Centro de Ajuda.')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b&&b.closest('#overview'))navigate(b.dataset.page)});document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));function navigate(page){document.querySelectorAll('.section').forEach(s=>s.classList.toggle('active',s.id===page));document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.getElementById('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');render();setTimeout(()=>showTutorial(false,state.ui.previewRole||'admin'),350);