/* Dashboards vivos e interativos — protótipo V1 */
(function(){
  const unitMap={t1:'Matriz',t2:'Unidade Centro',t3:'Unidade Shopping',t4:'Matriz',t5:'Unidade Centro',t6:'Unidade Shopping'};
  const units=['Todas as unidades','Matriz','Unidade Centro','Unidade Shopping'];
  const dash=state.ui.dashboard||{};
  dash.overviewPeriod=dash.overviewPeriod||'7d';
  dash.overviewUnit=dash.overviewUnit||'Todas as unidades';
  dash.analysisPeriod=dash.analysisPeriod||'30d';
  dash.analysisUnit=dash.analysisUnit||'Todas as unidades';
  dash.analysisCategory=dash.analysisCategory||'Todas as categorias';
  dash.analysisCriticality=dash.analysisCriticality||'Todas as criticidades';
  dash.customFrom=dash.customFrom||'2026-08-01';
  dash.customTo=dash.customTo||'2026-09-04';
  dash.selectedIssue=dash.selectedIssue||'';
  state.ui.dashboard=dash;

  const legacyOverview=window.renderOverview;
  const legacyAnalysis=window.renderAnalysis;

  function persistDash(){state.ui.dashboard=dash;localStorage.setItem('trielaV4',JSON.stringify(state));}
  function normDate(d){const x=new Date(d);return new Date(x.getFullYear(),x.getMonth(),x.getDate());}
  function unitForRun(r){return r.unit||unitMap[r.templateId]||'Matriz';}
  function unitForAction(a){const t=(state.templates||[]).find(x=>x.name===a.origin);return t?unitMap[t.id]||'Matriz':'Matriz';}
  function periodBounds(period){
    const now=new Date();let from,to=new Date(now.getFullYear(),now.getMonth(),now.getDate(),23,59,59,999);
    if(period==='custom'){from=new Date(dash.customFrom+'T00:00:00');to=new Date(dash.customTo+'T23:59:59');return{from,to};}
    const days=period==='90d'?90:period==='30d'?30:7;from=new Date(to);from.setDate(from.getDate()-(days-1));from.setHours(0,0,0,0);return{from,to};
  }
  function inPeriod(date,period){const{from,to}=periodBounds(period);const d=new Date(date);return d>=from&&d<=to;}
  function filterRuns(period,unit,includeOpen=true){return(state.runs||[]).filter(r=>(includeOpen||r.status==='completed')&&inPeriod(r.date,period)&&(unit==='Todas as unidades'||unitForRun(r)===unit));}
  function filterActions(period,unit){return(state.actions||[]).filter(a=>(unit==='Todas as unidades'||unitForAction(a)===unit));}
  function calc(period,unit){
    const all=filterRuns(period,unit,true),completed=all.filter(r=>r.status==='completed'),actions=filterActions(period,unit),pending=actions.filter(a=>a.status!=='done'),overdue=actions.filter(a=>a.status==='overdue');
    const execution=all.length?completed.length/all.length*100:0,compliance=completed.length?avg(completed.map(r=>r.compliance)):0,correction=actions.length?actions.filter(a=>a.status==='done').length/actions.length*100:100,punctuality=pending.length?(pending.length-overdue.length)/pending.length*100:100;
    const score=execution*.30+compliance*.35+correction*.20+punctuality*.15;
    return{all,completed,actions,pending,overdue,execution,compliance,correction,punctuality,score,nc:completed.reduce((s,r)=>s+(r.nc||0),0)};
  }
  function fmtPct(v){return Number(v||0).toFixed(1).replace('.',',')+'%';}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function labelPeriod(p){return p==='7d'?'7 dias':p==='30d'?'30 dias':p==='90d'?'90 dias':'Personalizado';}
  function dashSeries(period,unit){
    const completed=filterRuns(period,unit,false).slice().sort((a,b)=>new Date(a.date)-new Date(b.date));
    const base=completed.length?avg(completed.map(r=>r.compliance)):91.8;
    if(period==='7d'){
      const end=normDate(new Date()),vals=[],labels=[];let carry=Math.max(70,Math.min(100,base-3));
      for(let i=6;i>=0;i--){const d=new Date(end);d.setDate(d.getDate()-i);const day=completed.filter(r=>normDate(r.date).getTime()===d.getTime());if(day.length)carry=avg(day.map(r=>r.compliance));else carry=Math.max(70,Math.min(100,carry+(i%2?0.7:-0.2)));vals.push(Math.round(carry*10)/10);labels.push(i===0?'Hoje':['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'][d.getDay()]);}
      return{vals,labels};
    }
    const offsets=period==='90d'?[-6,-4.5,-3,-1.5,-.8,0]:[-4,-2.5,-1.6,-.7,.2,0];
    const vals=offsets.map((o,i)=>Math.max(70,Math.min(100,Math.round((base+o+(i%2?.3:0))*10)/10)));
    const labels=period==='90d'?['90d','75d','60d','45d','30d','Hoje']:['Sem 1','Sem 2','Sem 3','Sem 4','Sem 5','Hoje'];
    return{vals,labels};
  }
  function issueRows(period,unit,category,criticality){
    const out=[];filterRuns(period,unit,false).forEach(r=>{const t=tpl(r.templateId);(r.answers||[]).filter(a=>a.ok===false).forEach(a=>{const q=t?.questions?.find(x=>x.id===a.qid);if(!q)return;const item={name:q.title,category:t?.category||'Operações',critical:q.critical||'medium',date:r.date,unit:unitForRun(r),template:t?.name||'Checklist'};if(category!=='Todas as categorias'&&item.category!==category)return;if(criticality!=='Todas as criticidades'&&item.critical!==criticality)return;out.push(item);});});
    return out;
  }
  function issueSummary(items){const map={};items.forEach(x=>{const k=x.name;map[k]=map[k]||{...x,count:0,dates:[],units:new Set()};map[k].count++;map[k].dates.push(x.date);map[k].units.add(x.unit);});return Object.values(map).sort((a,b)=>b.count-a.count);}
  function categoryList(){return Array.from(new Set((state.templates||[]).map(t=>t.category).filter(Boolean))).sort();}
  function lastUpdated(el){
    if(!el)return;let live=el.querySelector('.live-row');if(!live){live=document.createElement('div');live.className='live-row';el.appendChild(live);}const now=new Date();live.innerHTML=`<span class="live-dot" aria-hidden="true"></span><span>Atualizado ${now.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</span><button type="button" class="live-refresh" data-dashboard-refresh>Atualizar agora</button>`;
  }
  function renderOverviewChart(period,unit){
    const {vals,labels}=dashSeries(period,unit),W=760,H=220,L=48,R=18,T=20,B=34,min=Math.max(60,Math.floor((Math.min(...vals)-5)/10)*10),max=100,x=i=>L+i*(W-L-R)/(vals.length-1),y=v=>T+(max-v)*(H-T-B)/(max-min||1);const pts=vals.map((v,i)=>`${x(i)},${y(v)}`).join(' '),area=`${L},${H-B} ${pts} ${x(vals.length-1)},${H-B}`,ticks=[min,Math.round((min+100)/2),90,100].filter((v,i,a)=>a.indexOf(v)===i).sort((a,b)=>a-b);const last=vals.at(-1);
    const svg=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" aria-label="Evolução da conformidade"><defs><linearGradient id="ovAreaGradientLive" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#7567ff" stop-opacity=".22"/><stop offset="100%" stop-color="#7567ff" stop-opacity="0"/></linearGradient></defs><g class="chart-grid">${ticks.map(t=>`<line x1="${L}" x2="${W-R}" y1="${y(t)}" y2="${y(t)}"/>`).join('')}</g>${ticks.map(t=>`<text class="chart-label" x="6" y="${y(t)+3}">${t}%</text>`).join('')}<polygon class="chart-area" points="${area}" style="fill:url(#ovAreaGradientLive)"/><polyline class="chart-line" points="${pts}"/>${vals.map((v,i)=>`<circle tabindex="0" role="button" aria-label="${labels[i]} ${fmtPct(v)}" class="chart-point ${i===vals.length-1?'chart-today':''}" data-dash-point="overview" data-index="${i}" data-label="${esc(labels[i])}" data-value="${v}" cx="${x(i)}" cy="${y(v)}" r="4"/>`).join('')}${labels.map((l,i)=>`<text class="chart-label" text-anchor="middle" x="${x(i)}" y="${H-7}">${esc(l)}</text>`).join('')}</svg><div class="chart-detail" id="overviewChartDetail"><span><strong>${esc(labels.at(-1))}</strong> • conformidade consolidada da seleção</span><span class="detail-pill">${fmtPct(last)}</span></div>`;
    const el=document.getElementById('complianceChart');if(el)el.innerHTML=svg;
  }
  function renderOverviewInteractive(){
    const m=calc(dash.overviewPeriod,dash.overviewUnit);const head=document.querySelector('#overview .overview-greeting');lastUpdated(head);
    const sel=document.getElementById('overviewUnit');if(sel){sel.value=dash.overviewUnit;sel.setAttribute('aria-label','Filtrar visão geral por unidade');}
    document.querySelectorAll('#overview .ov-periods button').forEach(b=>{const p=b.textContent.includes('7')?'7d':b.textContent.includes('30')?'30d':'90d';b.dataset.period=p;b.classList.toggle('active',p===dash.overviewPeriod);});
    const completed=m.completed.length,total=m.all.length,openNC=m.nc,overdue=m.overdue.length;
    const kpis=[{go:'analyze',icon:'↗',c:'purple',trend:m.compliance>=90?'Meta atingida':'Abaixo da meta',tc:m.compliance>=90?'up':'warn',main:fmtPct(m.compliance),small:'meta 90%',label:'Conformidade geral',bar:m.compliance,pc:'purple'},{go:'execute',icon:'✓',c:'teal',trend:`${completed} concluídos`,tc:'up',main:`${completed}`,small:`de ${total||0}`,label:'Checklists concluídos',bar:total?completed/total*100:0,pc:'teal'},{go:'routine',icon:'◷',c:'amber',trend:overdue?`${overdue} fora do prazo`:'No prazo',tc:overdue?'warn':'up',main:`${overdue}`,small:'atividades',label:'Execuções atrasadas',bar:Math.min(100,overdue*25),pc:'amber'},{go:'correct',icon:'△',c:'red',trend:`${Math.min(openNC,3)} críticas`,tc:'warn',main:`${openNC}`,small:'abertas',label:'Não conformidades',bar:Math.min(100,openNC*12),pc:'red'}];
    const box=document.getElementById('overviewKpis');if(box)box.innerHTML=kpis.map(x=>`<div class="ov-kpi" tabindex="0" role="button" data-go="${x.go}" aria-label="Abrir ${x.label}"><div class="ov-kpi-top"><div class="ov-icon ${x.c}">${x.icon}</div><span class="ov-trend ${x.tc}">${x.trend}</span></div><div class="ov-main"><strong>${x.main}</strong><small>${x.small}</small></div><div class="ov-label">${x.label}</div><div class="ov-progress ${x.pc}"><span style="width:${Math.max(0,Math.min(100,x.bar))}%"></span></div></div>`).join('');
    const score=Math.round(m.score),ps=document.getElementById('pulseScore'),ph=document.getElementById('pulseHealth');if(ps)ps.textContent=score;if(ph){ph.textContent=score>=85?'Saudável':score>=70?'Atenção':'Crítico';ph.title='Clique nos indicadores para abrir a análise correspondente';}
    const pm=document.getElementById('pulseMetrics');if(pm)pm.innerHTML=[['Execução no prazo',m.punctuality,'p1','routine'],['Conformidade',m.compliance,'p2','analyze'],['Ações resolvidas',m.correction,'p3','correct']].map(([l,v,c,go])=>`<div class="pulse-row" data-go="${go}" style="cursor:pointer" tabindex="0" role="button"><div class="pulse-top"><span>${l}</span><strong>${Math.round(v)}%</strong></div><div class="pulse-track"><span class="${c}" style="width:${Math.max(4,Math.min(100,v))}%"></span></div></div>`).join('');
    renderOverviewChart(dash.overviewPeriod,dash.overviewUnit);
    const issues=issueRows(dash.overviewPeriod,dash.overviewUnit,'Todas as categorias','Todas as criticidades'),byCat={};issues.forEach(x=>byCat[x.category]=(byCat[x.category]||0)+1);let cats=Object.entries(byCat).sort((a,b)=>b[1]-a[1]).slice(0,4);if(!cats.length)cats=categoryList().slice(0,4).map(c=>[c,0]);const maxCat=Math.max(1,...cats.map(x=>x[1]));const ol=document.getElementById('originList');if(ol)ol.innerHTML=cats.map(([n,v],i)=>`<div class="origin-row" tabindex="0" role="button" data-category="${esc(n)}"><span>${esc(n)}</span><div class="origin-track"><span class="c${i+1}" style="width:${Math.max(v?12:0,v/maxCat*100)}%"></span></div><strong>${v}</strong></div>`).join('')||'<div class="analysis-empty">Nenhum desvio nesta seleção.</div>';
    const rec=issueSummary(issues).slice(0,3),colors=['#ef5368','#f2a62e','#3196ed'];const rl=document.getElementById('recurrenceList');if(rl)rl.innerHTML=rec.length?rec.map((x,i)=>`<div class="recurrence-item" tabindex="0" role="button" data-issue="${esc(x.name)}"><span class="recurrence-dot" style="background:${colors[i]}"></span><span>${esc(x.name)}</span><strong>${x.count}x</strong></div>`).join(''):'<div class="analysis-empty">Sem reincidências nesta seleção.</div>';
    const templates=(state.templates||[]).filter(t=>dash.overviewUnit==='Todas as unidades'||(unitMap[t.id]||'Matriz')===dash.overviewUnit).slice(0,4),times=['08:00','09:30','11:00','18:00'];const al=document.getElementById('activityList');if(al)al.innerHTML=templates.length?templates.map((t,i)=>`<div class="activity-row" tabindex="0" role="button" data-template="${t.id}"><div class="activity-time">${times[i]||'14:00'}</div><div><div class="activity-title">${esc(t.name)}</div><div class="activity-unit">${esc(unitMap[t.id]||'Matriz')}</div></div><span class="activity-status ${i<2?'running':'pending'}">● ${i<2?'Em andamento':'Pendente'}</span></div>`).join(''):'<div class="analysis-empty">Nenhuma atividade para a unidade selecionada.</div>';
    const ov=document.getElementById('overview');if(ov){ov.classList.remove('dashboard-flash');void ov.offsetWidth;ov.classList.add('dashboard-flash');}
  }
  function analysisSeries(runs){
    const base=runs.length?avg(runs.map(r=>r.compliance)):91.8;const p=dash.analysisPeriod;const offsets=p==='90d'?[-7,-5,-3,-2,-1,0]:p==='custom'?[-5,-3,-2,-1,.5,0]:[-4,-2.7,-1.8,-.9,.2,0];return{vals:offsets.map((o,i)=>Math.max(65,Math.min(100,Math.round((base+o+(i%2?.25:0))*10)/10))),labels:p==='90d'?['90d','75d','60d','45d','30d','Hoje']:p==='custom'?['Início','20%','40%','60%','80%','Fim']:['Sem 1','Sem 2','Sem 3','Sem 4','Sem 5','Hoje']};
  }
  function renderAnalysisChart(runs){const{vals,labels}=analysisSeries(runs),W=710,H=190,L=36,R=14,T=14,B=28,min=Math.max(60,Math.floor((Math.min(...vals)-5)/10)*10),max=100,x=i=>L+i*(W-L-R)/(vals.length-1),y=v=>T+(max-v)*(H-T-B)/(max-min||1),pts=vals.map((v,i)=>`${x(i)},${y(v)}`).join(' '),area=`${L},${H-B} ${pts} ${x(vals.length-1)},${H-B}`,ticks=[min,Math.round((min+100)/2),90,100].filter((v,i,a)=>a.indexOf(v)===i).sort((a,b)=>a-b);const el=document.getElementById('analysisEvolution');if(!el)return;el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" aria-label="Evolução da conformidade no período"><defs><linearGradient id="analysisGradientLive" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#665af3" stop-opacity=".18"/><stop offset="100%" stop-color="#665af3" stop-opacity="0"/></linearGradient></defs>${ticks.map(t=>`<line class="analysis-gridline" x1="${L}" x2="${W-R}" y1="${y(t)}" y2="${y(t)}"/><text class="analysis-label" x="0" y="${y(t)+3}">${t}%</text>`).join('')}<polygon class="analysis-fill" style="fill:url(#analysisGradientLive)" points="${area}"/><polyline class="analysis-poly" points="${pts}"/>${vals.map((v,i)=>`<circle tabindex="0" role="button" aria-label="${labels[i]} ${fmtPct(v)}" class="analysis-point" data-dash-point="analysis" data-index="${i}" data-label="${esc(labels[i])}" data-value="${v}" cx="${x(i)}" cy="${y(v)}" r="4"/>`).join('')}${labels.map((l,i)=>`<text class="analysis-label" text-anchor="middle" x="${x(i)}" y="${H-6}">${esc(l)}</text>`).join('')}</svg><div class="chart-detail" id="analysisChartDetail"><span><strong>${esc(labels.at(-1))}</strong> • tendência da seleção atual</span><span class="detail-pill">${fmtPct(vals.at(-1))}</span></div>`;}
  function ensureAnalysisControls(){
    const head=document.querySelector('#analyze .analysis-head>div:first-child');lastUpdated(head);const f=document.querySelector('#analyze .analysis-filters');if(!f)return;
    if(!document.getElementById('analysisLiveControls')){f.insertAdjacentHTML('beforebegin',`<div class="analysis-live-controls" id="analysisLiveControls"><select id="analysisUnit" aria-label="Filtrar análise por unidade">${units.map(u=>`<option>${u}</option>`).join('')}</select><select id="analysisCategory" aria-label="Filtrar análise por categoria"><option>Todas as categorias</option>${categoryList().map(c=>`<option>${esc(c)}</option>`).join('')}</select></div>`);}
    const us=document.getElementById('analysisUnit'),cs=document.getElementById('analysisCategory');if(us)us.value=dash.analysisUnit;if(cs){cs.innerHTML=`<option>Todas as categorias</option>${categoryList().map(c=>`<option>${esc(c)}</option>`).join('')}`;cs.value=categoryList().includes(dash.analysisCategory)?dash.analysisCategory:'Todas as categorias';dash.analysisCategory=cs.value;}
    document.querySelectorAll('#analyze .analysis-filter').forEach(b=>{const txt=b.textContent.trim();if(txt.includes('30 dias'))b.dataset.period='30d';else if(txt.includes('90 dias'))b.dataset.period='90d';else if(txt.includes('01/08')||txt.includes('→'))b.dataset.period='custom';else if(txt.includes('Filtros'))b.dataset.openFilters='1';b.classList.toggle('active',b.dataset.period===dash.analysisPeriod);});
    renderFilterChips();
  }
  function renderFilterChips(){
    const host=document.querySelector('#analyze .analysis-head');if(!host)return;let row=document.getElementById('analysisActiveFilters');if(!row){row=document.createElement('div');row.id='analysisActiveFilters';row.className='dashboard-active-filter';host.insertAdjacentElement('afterend',row);}const chips=[];if(dash.analysisUnit!=='Todas as unidades')chips.push(['unit',dash.analysisUnit]);if(dash.analysisCategory!=='Todas as categorias')chips.push(['category',dash.analysisCategory]);if(dash.analysisCriticality!=='Todas as criticidades')chips.push(['criticality',criticalLabel(dash.analysisCriticality)]);if(dash.analysisPeriod==='custom')chips.push(['period',`${formatDateShort(dash.customFrom)} → ${formatDateShort(dash.customTo)}`]);row.innerHTML=chips.map(([k,v])=>`<span class="filter-chip">${esc(v)} <button type="button" aria-label="Remover filtro ${esc(v)}" data-remove-filter="${k}">×</button></span>`).join('');row.style.display=chips.length?'flex':'none';}
  function formatDateShort(s){const[a,m,d]=s.split('-');return`${d}/${m}/${a}`;}
  function criticalLabel(c){return({critical:'Crítica',high:'Alta',medium:'Média',low:'Baixa'})[c]||c;}
  function renderAnalysisInteractive(){
    ensureAnalysisControls();let runs=filterRuns(dash.analysisPeriod,dash.analysisUnit,false);if(dash.analysisCategory!=='Todas as categorias')runs=runs.filter(r=>tpl(r.templateId)?.category===dash.analysisCategory);const issues=issueRows(dash.analysisPeriod,dash.analysisUnit,dash.analysisCategory,dash.analysisCriticality),summary=issueSummary(issues),compliance=runs.length?avg(runs.map(r=>r.compliance)):0,critical=issues.filter(x=>['critical','high'].includes(x.critical)).length;
    const k=document.getElementById('analysisPremiumKpis');if(k)k.innerHTML=[{go:'overview',l:'Conformidade geral',v:fmtPct(compliance),i:'↗',bg:'#eeeaff',c:'#6757f2',tr:`${labelPeriod(dash.analysisPeriod)} • ${runs.length} execuções`},{go:'correct',l:'Total de NC',v:issues.length,i:'!',bg:'#fff4df',c:'#d88a00',tr:issues.length?'Clique para abrir tratativas':'Sem desvios no filtro'},{go:'correct',l:'NC críticas',v:critical,i:'△',bg:'#ffecef',c:'#e24b63',tr:critical?'Prioridade de tratamento':'Nenhuma crítica',bad:critical>0},{go:'correct',l:'Planos pendentes',v:filterActions(dash.analysisPeriod,dash.analysisUnit).filter(a=>a.status!=='done').length,i:'◷',bg:'#e5f9f4',c:'#14a98f',tr:'Acompanhamento de prazo'}].map(x=>`<div class="analysis-kpi" tabindex="0" role="button" data-go="${x.go}"><div class="ak-top"><span class="ak-label">${x.l}</span><span class="ak-icon" style="background:${x.bg};color:${x.c}">${x.i}</span></div><div class="ak-value">${x.v}</div><div class="ak-trend ${x.bad?'bad':''}">${x.tr}</div></div>`).join('');
    renderAnalysisChart(runs);
    const counts={};issueRows(dash.analysisPeriod,dash.analysisUnit,'Todas as categorias',dash.analysisCriticality).forEach(x=>counts[x.category]=(counts[x.category]||0)+1);let cats=Object.entries(counts).sort((a,b)=>b[1]-a[1]);const maxCat=Math.max(1,...cats.map(x=>x[1])),colors=['#7768f4','#2dbda8','#f2aa32','#e96377','#3196ed','#8c72d9'];const ce=document.getElementById('analysisCategories');if(ce)ce.innerHTML=cats.length?cats.map(([n,v],i)=>`<div class="cat-row ${dash.analysisCategory===n?'active':''}" tabindex="0" role="button" data-category="${esc(n)}"><span>${esc(n)}</span><div class="cat-track"><span style="width:${Math.max(8,v/maxCat*100)}%;background:${colors[i%colors.length]}"></span></div><strong>${v}</strong></div>`).join(''):'<div class="analysis-empty">Nenhuma categoria com desvios neste filtro.</div>';
    const ti=document.getElementById('analysisTopIssues');if(ti)ti.innerHTML=summary.length?summary.slice(0,5).map(x=>`<div class="nc-row ${dash.selectedIssue===x.name?'active':''}" tabindex="0" role="button" data-issue="${esc(x.name)}"><strong>${esc(x.name)}</strong><span>${esc(x.category)}</span><span><span class="crit-pill ${x.critical==='high'?'high':''}">${criticalLabel(x.critical)}</span></span><strong>${x.count}</strong></div>`).join(''):'<div class="analysis-empty">Nenhuma não conformidade encontrada.</div>';
    const rec=summary.filter(x=>x.count>=2).slice(0,4),re=document.getElementById('analysisRecurrences');if(re)re.innerHTML=rec.length?rec.map((x,i)=>`<div class="rec-card-item" tabindex="0" role="button" data-issue="${esc(x.name)}"><span class="dot" style="background:${['#e84e65','#f2a62e','#2d9bf0','#7768f4'][i%4]}"></span><div><strong>${esc(x.name)}</strong><small>${esc(x.category)} • ${x.count} ocorrências • ${x.units.size} unidade(s)</small></div><b>${x.count}x</b></div>`).join('')+`<button type="button" class="btn secondary" style="margin-top:10px;width:100%" data-root-cause>Filtrar reincidências →</button>`:'<div class="analysis-empty">Sem reincidências com os filtros atuais.</div>';
    const an=document.getElementById('analyze');if(an){an.classList.remove('dashboard-flash');void an.offsetWidth;an.classList.add('dashboard-flash');}
  }
  function showIssueDetail(name){
    const items=issueRows(dash.analysisPeriod,dash.analysisUnit,dash.analysisCategory,dash.analysisCriticality).filter(x=>x.name===name);if(!items.length){toast('Não há ocorrências desse item no filtro atual.');return;}dash.selectedIssue=name;persistDash();renderAnalysisInteractive();const first=items[0],last=items.slice().sort((a,b)=>new Date(b.date)-new Date(a.date))[0],root=document.getElementById('modalRoot');root.innerHTML=`<div class="modalback"><div class="modal" style="max-width:720px"><div class="modalhead"><div><div class="eyebrow">Drill-down da análise</div><h2 style="margin:4px 0;color:var(--navy)">${esc(name)}</h2><div class="sub">Clique nos dados para sair do resumo e entender a ocorrência.</div></div><button class="iconbtn" data-close-drill>×</button></div><div class="modalbody"><div class="drill-modal-grid"><div class="drill-stat"><span>Ocorrências</span><strong>${items.length}</strong></div><div class="drill-stat"><span>Criticidade</span><strong style="font-size:18px">${criticalLabel(first.critical)}</strong></div><div class="drill-stat"><span>Unidades afetadas</span><strong>${new Set(items.map(x=>x.unit)).size}</strong></div><div class="drill-stat"><span>Última ocorrência</span><strong style="font-size:17px">${new Date(last.date).toLocaleDateString('pt-BR')}</strong></div></div><div class="drill-history"><h3 style="margin:4px 0;color:var(--navy)">Histórico recente</h3>${items.slice().sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,6).map(x=>`<div class="drill-history-item"><span>${new Date(x.date).toLocaleDateString('pt-BR')}</span><strong>${esc(x.template)}</strong><span>${esc(x.unit)}</span></div>`).join('')}</div></div><div class="modalfooter"><button class="btn secondary" data-close-drill>Fechar</button><button class="btn" data-open-corrections>Ver não conformidades</button></div></div></div>`;
  }
  function openFilters(){
    const root=document.getElementById('modalRoot');root.innerHTML=`<div class="modalback"><div class="modal" style="max-width:620px"><div class="modalhead"><div><div class="eyebrow">Filtros avançados</div><h2 style="margin:4px 0;color:var(--navy)">Refinar análise</h2><div class="sub">Combine unidade, categoria e criticidade.</div></div><button class="iconbtn" data-close-filter>×</button></div><div class="modalbody"><div class="filter-form"><div class="field"><label>Unidade</label><select class="input" id="filterUnit">${units.map(u=>`<option ${u===dash.analysisUnit?'selected':''}>${u}</option>`).join('')}</select></div><div class="field"><label>Categoria</label><select class="input" id="filterCategory"><option>Todas as categorias</option>${categoryList().map(c=>`<option ${c===dash.analysisCategory?'selected':''}>${esc(c)}</option>`).join('')}</select></div><div class="field"><label>Criticidade</label><select class="input" id="filterCriticality"><option value="Todas as criticidades">Todas as criticidades</option><option value="critical" ${dash.analysisCriticality==='critical'?'selected':''}>Crítica</option><option value="high" ${dash.analysisCriticality==='high'?'selected':''}>Alta</option><option value="medium" ${dash.analysisCriticality==='medium'?'selected':''}>Média</option><option value="low" ${dash.analysisCriticality==='low'?'selected':''}>Baixa</option></select></div><div class="field"><label>Período</label><select class="input" id="filterPeriod"><option value="30d" ${dash.analysisPeriod==='30d'?'selected':''}>Últimos 30 dias</option><option value="90d" ${dash.analysisPeriod==='90d'?'selected':''}>Últimos 90 dias</option><option value="custom" ${dash.analysisPeriod==='custom'?'selected':''}>Personalizado</option></select></div></div></div><div class="modalfooter"><button class="btn secondary" data-clear-filters>Limpar filtros</button><button class="btn" data-apply-filters>Aplicar filtros</button></div></div></div>`;
  }
  function openCustomPeriod(){const root=document.getElementById('modalRoot');root.innerHTML=`<div class="modalback"><div class="modal" style="max-width:520px"><div class="modalhead"><div><div class="eyebrow">Período personalizado</div><h2 style="margin:4px 0;color:var(--navy)">Escolha as datas</h2></div><button class="iconbtn" data-close-custom>×</button></div><div class="modalbody"><div class="filter-form"><div class="field"><label>De</label><input class="input" type="date" id="customFrom" value="${dash.customFrom}"></div><div class="field"><label>Até</label><input class="input" type="date" id="customTo" value="${dash.customTo}"></div></div></div><div class="modalfooter"><button class="btn secondary" data-close-custom>Cancelar</button><button class="btn" data-apply-custom>Aplicar período</button></div></div></div>`;}

  window.renderOverview=function(){legacyOverview();renderOverviewInteractive();};
  window.renderAnalysis=function(){legacyAnalysis();renderAnalysisInteractive();};
  window.setAnalysisPeriod=function(p){if(p==='custom'){openCustomPeriod();return;}analysisPeriod=p;dash.analysisPeriod=p;persistDash();renderAnalysisInteractive();};

  document.addEventListener('change',e=>{
    if(e.target.id==='overviewUnit'){dash.overviewUnit=e.target.value;persistDash();renderOverviewInteractive();}
    if(e.target.id==='analysisUnit'){dash.analysisUnit=e.target.value;persistDash();renderAnalysisInteractive();}
    if(e.target.id==='analysisCategory'){dash.analysisCategory=e.target.value;persistDash();renderAnalysisInteractive();}
  });
  document.addEventListener('click',e=>{
    const period=e.target.closest('#overview .ov-periods button[data-period]');if(period){dash.overviewPeriod=period.dataset.period;persistDash();renderOverviewInteractive();return;}
    const refresh=e.target.closest('[data-dashboard-refresh]');if(refresh){renderOverviewInteractive();renderAnalysisInteractive();toast('Painéis atualizados com os dados atuais.');return;}
    const go=e.target.closest('[data-go]');if(go){navigate(go.dataset.go);return;}
    const point=e.target.closest('[data-dash-point]');if(point){document.querySelectorAll(`.${point.classList.contains('analysis-point')?'analysis-point':'chart-point'}`).forEach(x=>x.classList.remove('selected'));point.classList.add('selected');const id=point.dataset.dashPoint==='analysis'?'analysisChartDetail':'overviewChartDetail',detail=document.getElementById(id);if(detail)detail.innerHTML=`<span><strong>${esc(point.dataset.label)}</strong> • ponto selecionado do gráfico</span><span class="detail-pill">${fmtPct(point.dataset.value)}</span>`;return;}
    const origin=e.target.closest('#overview .origin-row[data-category]');if(origin){dash.analysisCategory=origin.dataset.category;dash.analysisUnit=dash.overviewUnit;persistDash();navigate('analyze');renderAnalysisInteractive();toast(`Análises filtradas por ${origin.dataset.category}.`);return;}
    const activity=e.target.closest('#overview .activity-row[data-template]');if(activity){startRun(activity.dataset.template);return;}
    const cat=e.target.closest('#analyze .cat-row[data-category]');if(cat){dash.analysisCategory=dash.analysisCategory===cat.dataset.category?'Todas as categorias':cat.dataset.category;persistDash();renderAnalysisInteractive();return;}
    const issue=e.target.closest('[data-issue]');if(issue){showIssueDetail(issue.dataset.issue);return;}
    const filterBtn=e.target.closest('#analyze [data-open-filters]')||e.target.closest('#analyze .analysis-filter[data-open-filters]');if(filterBtn){openFilters();return;}
    const anyFilter=e.target.closest('#analyze .analysis-filter');if(anyFilter&&anyFilter.textContent.includes('Filtros')){openFilters();return;}
    const rootCause=e.target.closest('[data-root-cause]');if(rootCause){dash.analysisCriticality='critical';persistDash();renderAnalysisInteractive();toast('Filtro aplicado: somente criticidade crítica.');return;}
    const remove=e.target.closest('[data-remove-filter]');if(remove){const k=remove.dataset.removeFilter;if(k==='unit')dash.analysisUnit='Todas as unidades';if(k==='category')dash.analysisCategory='Todas as categorias';if(k==='criticality')dash.analysisCriticality='Todas as criticidades';if(k==='period')dash.analysisPeriod='30d';persistDash();renderAnalysisInteractive();return;}
    if(e.target.closest('[data-close-drill],[data-close-filter],[data-close-custom]')){closeModal();return;}
    if(e.target.closest('[data-open-corrections]')){closeModal();navigate('correct');return;}
    if(e.target.closest('[data-clear-filters]')){dash.analysisUnit='Todas as unidades';dash.analysisCategory='Todas as categorias';dash.analysisCriticality='Todas as criticidades';dash.analysisPeriod='30d';persistDash();closeModal();renderAnalysisInteractive();return;}
    if(e.target.closest('[data-apply-filters]')){dash.analysisUnit=document.getElementById('filterUnit').value;dash.analysisCategory=document.getElementById('filterCategory').value;dash.analysisCriticality=document.getElementById('filterCriticality').value;const p=document.getElementById('filterPeriod').value;dash.analysisPeriod=p;persistDash();closeModal();if(p==='custom')openCustomPeriod();else renderAnalysisInteractive();return;}
    if(e.target.closest('[data-apply-custom]')){const from=document.getElementById('customFrom').value,to=document.getElementById('customTo').value;if(!from||!to||from>to){toast('Confira as datas do período personalizado.');return;}dash.customFrom=from;dash.customTo=to;dash.analysisPeriod='custom';analysisPeriod='custom';persistDash();closeModal();renderAnalysisInteractive();return;}
  });
  document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[role="button"][data-go],[role="button"][data-category],[role="button"][data-issue],[role="button"][data-template],.chart-point,.analysis-point')){e.preventDefault();e.target.click();}});
  window.addEventListener('storage',e=>{if(e.key==='trielaV4'&&e.newValue){try{state=JSON.parse(e.newValue);state.ui=state.ui||{};state.ui.dashboard=state.ui.dashboard||dash;renderOverviewInteractive();renderAnalysisInteractive();toast('Dados atualizados em outra aba.');}catch(_){}}});

  renderOverviewInteractive();renderAnalysisInteractive();
})();
